{{- if include "otelcol-fritzbox.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otelcol-fritzbox.fullname" . }}
  labels:
    {{- include "otelcol-fritzbox.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and (not .Values.fritzbox.existingSecret) .Values.fritzbox.username }}
  fritzbox-username: {{ .Values.fritzbox.username | quote }}
  fritzbox-password: {{ .Values.fritzbox.password | quote }}
  {{- end }}
  {{- if and (include "otelcol-fritzbox.otlpBasicAuth" .) (not .Values.otlp.existingSecret) }}
  otlp-username: {{ .Values.otlp.username | quote }}
  otlp-password: {{ .Values.otlp.password | quote }}
  {{- end }}
{{- end }}
