apiVersion: v1
kind: Service
metadata:
  name: {{ include "otelcol-fritzbox.fullname" . }}
  labels:
    {{- include "otelcol-fritzbox.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "otelcol-fritzbox.selectorLabels" . | nindent 4 }}
  ports:
    - name: health
      port: 13133
      targetPort: health
      protocol: TCP
    - name: metrics
      port: 8888
      targetPort: metrics
      protocol: TCP
