// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					FritzboxDeviceUptime: FritzboxDeviceUptimeMetricConfig{
						Enabled: true,
					},
					FritzboxDslAttenuation: FritzboxDslAttenuationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxDslAttenuationMetricAttributeKey{FritzboxDslAttenuationMetricAttributeKeyNetworkIoDirection},
					},
					FritzboxDslErrorSeconds: FritzboxDslErrorSecondsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []FritzboxDslErrorSecondsMetricAttributeKey{FritzboxDslErrorSecondsMetricAttributeKeySeverity},
					},
					FritzboxDslNoiseMargin: FritzboxDslNoiseMarginMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxDslNoiseMarginMetricAttributeKey{FritzboxDslNoiseMarginMetricAttributeKeyNetworkIoDirection},
					},
					FritzboxDslRateCurrent: FritzboxDslRateCurrentMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxDslRateCurrentMetricAttributeKey{FritzboxDslRateCurrentMetricAttributeKeyNetworkIoDirection},
					},
					FritzboxDslRateMax: FritzboxDslRateMaxMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxDslRateMaxMetricAttributeKey{FritzboxDslRateMaxMetricAttributeKeyNetworkIoDirection},
					},
					FritzboxHostsActive: FritzboxHostsActiveMetricConfig{
						Enabled: true,
					},
					FritzboxHostsInfo: FritzboxHostsInfoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxHostsInfoMetricAttributeKey{FritzboxHostsInfoMetricAttributeKeyHostname, FritzboxHostsInfoMetricAttributeKeyIP, FritzboxHostsInfoMetricAttributeKeyMac, FritzboxHostsInfoMetricAttributeKeyInterfaceType, FritzboxHostsInfoMetricAttributeKeyActive, FritzboxHostsInfoMetricAttributeKeyGuest, FritzboxHostsInfoMetricAttributeKeyFriendlyName},
					},
					FritzboxHostsTotal: FritzboxHostsTotalMetricConfig{
						Enabled: true,
					},
					FritzboxWanConnectionStatus: FritzboxWanConnectionStatusMetricConfig{
						Enabled: true,
					},
					FritzboxWanConnectionUptime: FritzboxWanConnectionUptimeMetricConfig{
						Enabled: true,
					},
					FritzboxWanExternalIP: FritzboxWanExternalIPMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxWanExternalIPMetricAttributeKey{FritzboxWanExternalIPMetricAttributeKeyExternalIP},
					},
					FritzboxWlanChannel: FritzboxWlanChannelMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxWlanChannelMetricAttributeKey{FritzboxWlanChannelMetricAttributeKeyHwID, FritzboxWlanChannelMetricAttributeKeySsid},
					},
					FritzboxWlanClients: FritzboxWlanClientsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxWlanClientsMetricAttributeKey{FritzboxWlanClientsMetricAttributeKeyHwID, FritzboxWlanClientsMetricAttributeKeySsid},
					},
					HwErrors: HwErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwErrorsMetricAttributeKey{HwErrorsMetricAttributeKeyHwID, HwErrorsMetricAttributeKeyErrorType, HwErrorsMetricAttributeKeyNetworkIoDirection},
					},
					HwNetworkBandwidthLimit: HwNetworkBandwidthLimitMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwNetworkBandwidthLimitMetricAttributeKey{HwNetworkBandwidthLimitMetricAttributeKeyHwID},
					},
					HwNetworkBandwidthUtilization: HwNetworkBandwidthUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwNetworkBandwidthUtilizationMetricAttributeKey{HwNetworkBandwidthUtilizationMetricAttributeKeyHwID, HwNetworkBandwidthUtilizationMetricAttributeKeyNetworkIoDirection},
					},
					HwNetworkIo: HwNetworkIoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwNetworkIoMetricAttributeKey{HwNetworkIoMetricAttributeKeyHwID, HwNetworkIoMetricAttributeKeyHwName, HwNetworkIoMetricAttributeKeyNetworkIoDirection},
					},
					HwNetworkPackets: HwNetworkPacketsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwNetworkPacketsMetricAttributeKey{HwNetworkPacketsMetricAttributeKeyHwID, HwNetworkPacketsMetricAttributeKeyHwName, HwNetworkPacketsMetricAttributeKeyNetworkIoDirection},
					},
					HwNetworkUp: HwNetworkUpMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwNetworkUpMetricAttributeKey{HwNetworkUpMetricAttributeKeyHwID, HwNetworkUpMetricAttributeKeyHwName},
					},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					FritzboxDeviceUptime: FritzboxDeviceUptimeMetricConfig{
						Enabled: false,
					},
					FritzboxDslAttenuation: FritzboxDslAttenuationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxDslAttenuationMetricAttributeKey{FritzboxDslAttenuationMetricAttributeKeyNetworkIoDirection},
					},
					FritzboxDslErrorSeconds: FritzboxDslErrorSecondsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []FritzboxDslErrorSecondsMetricAttributeKey{FritzboxDslErrorSecondsMetricAttributeKeySeverity},
					},
					FritzboxDslNoiseMargin: FritzboxDslNoiseMarginMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxDslNoiseMarginMetricAttributeKey{FritzboxDslNoiseMarginMetricAttributeKeyNetworkIoDirection},
					},
					FritzboxDslRateCurrent: FritzboxDslRateCurrentMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxDslRateCurrentMetricAttributeKey{FritzboxDslRateCurrentMetricAttributeKeyNetworkIoDirection},
					},
					FritzboxDslRateMax: FritzboxDslRateMaxMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxDslRateMaxMetricAttributeKey{FritzboxDslRateMaxMetricAttributeKeyNetworkIoDirection},
					},
					FritzboxHostsActive: FritzboxHostsActiveMetricConfig{
						Enabled: false,
					},
					FritzboxHostsInfo: FritzboxHostsInfoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxHostsInfoMetricAttributeKey{FritzboxHostsInfoMetricAttributeKeyHostname, FritzboxHostsInfoMetricAttributeKeyIP, FritzboxHostsInfoMetricAttributeKeyMac, FritzboxHostsInfoMetricAttributeKeyInterfaceType, FritzboxHostsInfoMetricAttributeKeyActive, FritzboxHostsInfoMetricAttributeKeyGuest, FritzboxHostsInfoMetricAttributeKeyFriendlyName},
					},
					FritzboxHostsTotal: FritzboxHostsTotalMetricConfig{
						Enabled: false,
					},
					FritzboxWanConnectionStatus: FritzboxWanConnectionStatusMetricConfig{
						Enabled: false,
					},
					FritzboxWanConnectionUptime: FritzboxWanConnectionUptimeMetricConfig{
						Enabled: false,
					},
					FritzboxWanExternalIP: FritzboxWanExternalIPMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxWanExternalIPMetricAttributeKey{FritzboxWanExternalIPMetricAttributeKeyExternalIP},
					},
					FritzboxWlanChannel: FritzboxWlanChannelMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxWlanChannelMetricAttributeKey{FritzboxWlanChannelMetricAttributeKeyHwID, FritzboxWlanChannelMetricAttributeKeySsid},
					},
					FritzboxWlanClients: FritzboxWlanClientsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []FritzboxWlanClientsMetricAttributeKey{FritzboxWlanClientsMetricAttributeKeyHwID, FritzboxWlanClientsMetricAttributeKeySsid},
					},
					HwErrors: HwErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwErrorsMetricAttributeKey{HwErrorsMetricAttributeKeyHwID, HwErrorsMetricAttributeKeyErrorType, HwErrorsMetricAttributeKeyNetworkIoDirection},
					},
					HwNetworkBandwidthLimit: HwNetworkBandwidthLimitMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwNetworkBandwidthLimitMetricAttributeKey{HwNetworkBandwidthLimitMetricAttributeKeyHwID},
					},
					HwNetworkBandwidthUtilization: HwNetworkBandwidthUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwNetworkBandwidthUtilizationMetricAttributeKey{HwNetworkBandwidthUtilizationMetricAttributeKeyHwID, HwNetworkBandwidthUtilizationMetricAttributeKeyNetworkIoDirection},
					},
					HwNetworkIo: HwNetworkIoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwNetworkIoMetricAttributeKey{HwNetworkIoMetricAttributeKeyHwID, HwNetworkIoMetricAttributeKeyHwName, HwNetworkIoMetricAttributeKeyNetworkIoDirection},
					},
					HwNetworkPackets: HwNetworkPacketsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []HwNetworkPacketsMetricAttributeKey{HwNetworkPacketsMetricAttributeKeyHwID, HwNetworkPacketsMetricAttributeKeyHwName, HwNetworkPacketsMetricAttributeKeyNetworkIoDirection},
					},
					HwNetworkUp: HwNetworkUpMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []HwNetworkUpMetricAttributeKey{HwNetworkUpMetricAttributeKeyHwID, HwNetworkUpMetricAttributeKeyHwName},
					},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(FritzboxDeviceUptimeMetricConfig{}, FritzboxDslAttenuationMetricConfig{}, FritzboxDslErrorSecondsMetricConfig{}, FritzboxDslNoiseMarginMetricConfig{}, FritzboxDslRateCurrentMetricConfig{}, FritzboxDslRateMaxMetricConfig{}, FritzboxHostsActiveMetricConfig{}, FritzboxHostsInfoMetricConfig{}, FritzboxHostsTotalMetricConfig{}, FritzboxWanConnectionStatusMetricConfig{}, FritzboxWanConnectionUptimeMetricConfig{}, FritzboxWanExternalIPMetricConfig{}, FritzboxWlanChannelMetricConfig{}, FritzboxWlanClientsMetricConfig{}, HwErrorsMetricConfig{}, HwNetworkBandwidthLimitMetricConfig{}, HwNetworkBandwidthUtilizationMetricConfig{}, HwNetworkIoMetricConfig{}, HwNetworkPacketsMetricConfig{}, HwNetworkUpMetricConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func TestFritzboxDslAttenuationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().FritzboxDslAttenuation
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []FritzboxDslAttenuationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric fritzbox.dsl.attenuation doesn't have an attribute invalid, valid attributes: [network.io.direction]")

	cfg = DefaultMetricsConfig().FritzboxDslAttenuation
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestFritzboxDslErrorSecondsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().FritzboxDslErrorSeconds
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []FritzboxDslErrorSecondsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric fritzbox.dsl.error_seconds doesn't have an attribute invalid, valid attributes: [severity]")

	cfg = DefaultMetricsConfig().FritzboxDslErrorSeconds
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestFritzboxDslNoiseMarginMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().FritzboxDslNoiseMargin
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []FritzboxDslNoiseMarginMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric fritzbox.dsl.noise_margin doesn't have an attribute invalid, valid attributes: [network.io.direction]")

	cfg = DefaultMetricsConfig().FritzboxDslNoiseMargin
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestFritzboxDslRateCurrentMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().FritzboxDslRateCurrent
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []FritzboxDslRateCurrentMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric fritzbox.dsl.rate.current doesn't have an attribute invalid, valid attributes: [network.io.direction]")

	cfg = DefaultMetricsConfig().FritzboxDslRateCurrent
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestFritzboxDslRateMaxMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().FritzboxDslRateMax
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []FritzboxDslRateMaxMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric fritzbox.dsl.rate.max doesn't have an attribute invalid, valid attributes: [network.io.direction]")

	cfg = DefaultMetricsConfig().FritzboxDslRateMax
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestFritzboxHostsInfoMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().FritzboxHostsInfo
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []FritzboxHostsInfoMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric fritzbox.hosts.info doesn't have an attribute invalid, valid attributes: [hostname, ip, mac, interface_type, active, guest, friendly_name]")

	cfg = DefaultMetricsConfig().FritzboxHostsInfo
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestFritzboxWanExternalIPMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().FritzboxWanExternalIP
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []FritzboxWanExternalIPMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric fritzbox.wan.external_ip doesn't have an attribute invalid, valid attributes: [external_ip]")

	cfg = DefaultMetricsConfig().FritzboxWanExternalIP
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestFritzboxWlanChannelMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().FritzboxWlanChannel
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []FritzboxWlanChannelMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric fritzbox.wlan.channel doesn't have an attribute invalid, valid attributes: [hw.id, ssid]")

	cfg = DefaultMetricsConfig().FritzboxWlanChannel
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestFritzboxWlanClientsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().FritzboxWlanClients
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []FritzboxWlanClientsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric fritzbox.wlan.clients doesn't have an attribute invalid, valid attributes: [hw.id, ssid]")

	cfg = DefaultMetricsConfig().FritzboxWlanClients
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwErrorsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwErrors
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwErrorsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.errors doesn't have an attribute invalid, valid attributes: [hw.id, error.type, network.io.direction]")

	cfg = DefaultMetricsConfig().HwErrors
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwNetworkBandwidthLimitMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwNetworkBandwidthLimit
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwNetworkBandwidthLimitMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.network.bandwidth.limit doesn't have an attribute invalid, valid attributes: [hw.id]")

	cfg = DefaultMetricsConfig().HwNetworkBandwidthLimit
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwNetworkBandwidthUtilizationMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwNetworkBandwidthUtilization
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwNetworkBandwidthUtilizationMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.network.bandwidth.utilization doesn't have an attribute invalid, valid attributes: [hw.id, network.io.direction]")

	cfg = DefaultMetricsConfig().HwNetworkBandwidthUtilization
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwNetworkIoMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwNetworkIo
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwNetworkIoMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.network.io doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, network.io.direction]")

	cfg = DefaultMetricsConfig().HwNetworkIo
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwNetworkPacketsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwNetworkPackets
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwNetworkPacketsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.network.packets doesn't have an attribute invalid, valid attributes: [hw.id, hw.name, network.io.direction]")

	cfg = DefaultMetricsConfig().HwNetworkPackets
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestHwNetworkUpMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().HwNetworkUp
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []HwNetworkUpMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric hw.network.up doesn't have an attribute invalid, valid attributes: [hw.id, hw.name]")

	cfg = DefaultMetricsConfig().HwNetworkUp
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}
