// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/fritzbox component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("fritzbox")
	ScopeName = "github.com/mbaykara/fritzotel-receiver/receiver/fritzbox"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
