// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"

	"go.opentelemetry.io/collector/confmap"
)

// FritzboxDeviceUptimeMetricConfig provides config for the fritzbox.device.uptime metric.
type FritzboxDeviceUptimeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *FritzboxDeviceUptimeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// FritzboxDslAttenuationMetricAttributeKey specifies the key of an attribute for the fritzbox.dsl.attenuation metric.
type FritzboxDslAttenuationMetricAttributeKey string

const (
	FritzboxDslAttenuationMetricAttributeKeyNetworkIoDirection FritzboxDslAttenuationMetricAttributeKey = "network.io.direction"
)

// FritzboxDslAttenuationMetricConfig provides config for the fritzbox.dsl.attenuation metric.
type FritzboxDslAttenuationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                     `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []FritzboxDslAttenuationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *FritzboxDslAttenuationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *FritzboxDslAttenuationMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case FritzboxDslAttenuationMetricAttributeKeyNetworkIoDirection:
		default:
			return fmt.Errorf("metric fritzbox.dsl.attenuation doesn't have an attribute %v, valid attributes: [network.io.direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// FritzboxDslErrorSecondsMetricAttributeKey specifies the key of an attribute for the fritzbox.dsl.error_seconds metric.
type FritzboxDslErrorSecondsMetricAttributeKey string

const (
	FritzboxDslErrorSecondsMetricAttributeKeySeverity FritzboxDslErrorSecondsMetricAttributeKey = "severity"
)

// FritzboxDslErrorSecondsMetricConfig provides config for the fritzbox.dsl.error_seconds metric.
type FritzboxDslErrorSecondsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                      `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []FritzboxDslErrorSecondsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *FritzboxDslErrorSecondsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *FritzboxDslErrorSecondsMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case FritzboxDslErrorSecondsMetricAttributeKeySeverity:
		default:
			return fmt.Errorf("metric fritzbox.dsl.error_seconds doesn't have an attribute %v, valid attributes: [severity]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// FritzboxDslNoiseMarginMetricAttributeKey specifies the key of an attribute for the fritzbox.dsl.noise_margin metric.
type FritzboxDslNoiseMarginMetricAttributeKey string

const (
	FritzboxDslNoiseMarginMetricAttributeKeyNetworkIoDirection FritzboxDslNoiseMarginMetricAttributeKey = "network.io.direction"
)

// FritzboxDslNoiseMarginMetricConfig provides config for the fritzbox.dsl.noise_margin metric.
type FritzboxDslNoiseMarginMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                     `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []FritzboxDslNoiseMarginMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *FritzboxDslNoiseMarginMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *FritzboxDslNoiseMarginMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case FritzboxDslNoiseMarginMetricAttributeKeyNetworkIoDirection:
		default:
			return fmt.Errorf("metric fritzbox.dsl.noise_margin doesn't have an attribute %v, valid attributes: [network.io.direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// FritzboxDslRateCurrentMetricAttributeKey specifies the key of an attribute for the fritzbox.dsl.rate.current metric.
type FritzboxDslRateCurrentMetricAttributeKey string

const (
	FritzboxDslRateCurrentMetricAttributeKeyNetworkIoDirection FritzboxDslRateCurrentMetricAttributeKey = "network.io.direction"
)

// FritzboxDslRateCurrentMetricConfig provides config for the fritzbox.dsl.rate.current metric.
type FritzboxDslRateCurrentMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                     `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []FritzboxDslRateCurrentMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *FritzboxDslRateCurrentMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *FritzboxDslRateCurrentMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case FritzboxDslRateCurrentMetricAttributeKeyNetworkIoDirection:
		default:
			return fmt.Errorf("metric fritzbox.dsl.rate.current doesn't have an attribute %v, valid attributes: [network.io.direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// FritzboxDslRateMaxMetricAttributeKey specifies the key of an attribute for the fritzbox.dsl.rate.max metric.
type FritzboxDslRateMaxMetricAttributeKey string

const (
	FritzboxDslRateMaxMetricAttributeKeyNetworkIoDirection FritzboxDslRateMaxMetricAttributeKey = "network.io.direction"
)

// FritzboxDslRateMaxMetricConfig provides config for the fritzbox.dsl.rate.max metric.
type FritzboxDslRateMaxMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                 `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []FritzboxDslRateMaxMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *FritzboxDslRateMaxMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *FritzboxDslRateMaxMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case FritzboxDslRateMaxMetricAttributeKeyNetworkIoDirection:
		default:
			return fmt.Errorf("metric fritzbox.dsl.rate.max doesn't have an attribute %v, valid attributes: [network.io.direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// FritzboxHostsActiveMetricConfig provides config for the fritzbox.hosts.active metric.
type FritzboxHostsActiveMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *FritzboxHostsActiveMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// FritzboxHostsInfoMetricAttributeKey specifies the key of an attribute for the fritzbox.hosts.info metric.
type FritzboxHostsInfoMetricAttributeKey string

const (
	FritzboxHostsInfoMetricAttributeKeyHostname      FritzboxHostsInfoMetricAttributeKey = "hostname"
	FritzboxHostsInfoMetricAttributeKeyIP            FritzboxHostsInfoMetricAttributeKey = "ip"
	FritzboxHostsInfoMetricAttributeKeyMac           FritzboxHostsInfoMetricAttributeKey = "mac"
	FritzboxHostsInfoMetricAttributeKeyInterfaceType FritzboxHostsInfoMetricAttributeKey = "interface_type"
	FritzboxHostsInfoMetricAttributeKeyActive        FritzboxHostsInfoMetricAttributeKey = "active"
	FritzboxHostsInfoMetricAttributeKeyGuest         FritzboxHostsInfoMetricAttributeKey = "guest"
	FritzboxHostsInfoMetricAttributeKeyFriendlyName  FritzboxHostsInfoMetricAttributeKey = "friendly_name"
)

// FritzboxHostsInfoMetricConfig provides config for the fritzbox.hosts.info metric.
type FritzboxHostsInfoMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []FritzboxHostsInfoMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *FritzboxHostsInfoMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *FritzboxHostsInfoMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case FritzboxHostsInfoMetricAttributeKeyHostname, FritzboxHostsInfoMetricAttributeKeyIP, FritzboxHostsInfoMetricAttributeKeyMac, FritzboxHostsInfoMetricAttributeKeyInterfaceType, FritzboxHostsInfoMetricAttributeKeyActive, FritzboxHostsInfoMetricAttributeKeyGuest, FritzboxHostsInfoMetricAttributeKeyFriendlyName:
		default:
			return fmt.Errorf("metric fritzbox.hosts.info doesn't have an attribute %v, valid attributes: [hostname, ip, mac, interface_type, active, guest, friendly_name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// FritzboxHostsTotalMetricConfig provides config for the fritzbox.hosts.total metric.
type FritzboxHostsTotalMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *FritzboxHostsTotalMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// FritzboxWanConnectionStatusMetricConfig provides config for the fritzbox.wan.connection.status metric.
type FritzboxWanConnectionStatusMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *FritzboxWanConnectionStatusMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// FritzboxWanConnectionUptimeMetricConfig provides config for the fritzbox.wan.connection.uptime metric.
type FritzboxWanConnectionUptimeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *FritzboxWanConnectionUptimeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// FritzboxWanExternalIPMetricAttributeKey specifies the key of an attribute for the fritzbox.wan.external_ip metric.
type FritzboxWanExternalIPMetricAttributeKey string

const (
	FritzboxWanExternalIPMetricAttributeKeyExternalIP FritzboxWanExternalIPMetricAttributeKey = "external_ip"
)

// FritzboxWanExternalIPMetricConfig provides config for the fritzbox.wan.external_ip metric.
type FritzboxWanExternalIPMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                    `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []FritzboxWanExternalIPMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *FritzboxWanExternalIPMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *FritzboxWanExternalIPMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case FritzboxWanExternalIPMetricAttributeKeyExternalIP:
		default:
			return fmt.Errorf("metric fritzbox.wan.external_ip doesn't have an attribute %v, valid attributes: [external_ip]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// FritzboxWlanChannelMetricAttributeKey specifies the key of an attribute for the fritzbox.wlan.channel metric.
type FritzboxWlanChannelMetricAttributeKey string

const (
	FritzboxWlanChannelMetricAttributeKeyHwID FritzboxWlanChannelMetricAttributeKey = "hw.id"
	FritzboxWlanChannelMetricAttributeKeySsid FritzboxWlanChannelMetricAttributeKey = "ssid"
)

// FritzboxWlanChannelMetricConfig provides config for the fritzbox.wlan.channel metric.
type FritzboxWlanChannelMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                  `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []FritzboxWlanChannelMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *FritzboxWlanChannelMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *FritzboxWlanChannelMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case FritzboxWlanChannelMetricAttributeKeyHwID, FritzboxWlanChannelMetricAttributeKeySsid:
		default:
			return fmt.Errorf("metric fritzbox.wlan.channel doesn't have an attribute %v, valid attributes: [hw.id, ssid]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// FritzboxWlanClientsMetricAttributeKey specifies the key of an attribute for the fritzbox.wlan.clients metric.
type FritzboxWlanClientsMetricAttributeKey string

const (
	FritzboxWlanClientsMetricAttributeKeyHwID FritzboxWlanClientsMetricAttributeKey = "hw.id"
	FritzboxWlanClientsMetricAttributeKeySsid FritzboxWlanClientsMetricAttributeKey = "ssid"
)

// FritzboxWlanClientsMetricConfig provides config for the fritzbox.wlan.clients metric.
type FritzboxWlanClientsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                  `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []FritzboxWlanClientsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *FritzboxWlanClientsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *FritzboxWlanClientsMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case FritzboxWlanClientsMetricAttributeKeyHwID, FritzboxWlanClientsMetricAttributeKeySsid:
		default:
			return fmt.Errorf("metric fritzbox.wlan.clients doesn't have an attribute %v, valid attributes: [hw.id, ssid]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// HwErrorsMetricAttributeKey specifies the key of an attribute for the hw.errors metric.
type HwErrorsMetricAttributeKey string

const (
	HwErrorsMetricAttributeKeyHwID               HwErrorsMetricAttributeKey = "hw.id"
	HwErrorsMetricAttributeKeyErrorType          HwErrorsMetricAttributeKey = "error.type"
	HwErrorsMetricAttributeKeyNetworkIoDirection HwErrorsMetricAttributeKey = "network.io.direction"
)

// HwErrorsMetricConfig provides config for the hw.errors metric.
type HwErrorsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                       `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []HwErrorsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *HwErrorsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *HwErrorsMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case HwErrorsMetricAttributeKeyHwID, HwErrorsMetricAttributeKeyErrorType, HwErrorsMetricAttributeKeyNetworkIoDirection:
		default:
			return fmt.Errorf("metric hw.errors doesn't have an attribute %v, valid attributes: [hw.id, error.type, network.io.direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// HwNetworkBandwidthLimitMetricAttributeKey specifies the key of an attribute for the hw.network.bandwidth.limit metric.
type HwNetworkBandwidthLimitMetricAttributeKey string

const (
	HwNetworkBandwidthLimitMetricAttributeKeyHwID HwNetworkBandwidthLimitMetricAttributeKey = "hw.id"
)

// HwNetworkBandwidthLimitMetricConfig provides config for the hw.network.bandwidth.limit metric.
type HwNetworkBandwidthLimitMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                      `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []HwNetworkBandwidthLimitMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *HwNetworkBandwidthLimitMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *HwNetworkBandwidthLimitMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case HwNetworkBandwidthLimitMetricAttributeKeyHwID:
		default:
			return fmt.Errorf("metric hw.network.bandwidth.limit doesn't have an attribute %v, valid attributes: [hw.id]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// HwNetworkBandwidthUtilizationMetricAttributeKey specifies the key of an attribute for the hw.network.bandwidth.utilization metric.
type HwNetworkBandwidthUtilizationMetricAttributeKey string

const (
	HwNetworkBandwidthUtilizationMetricAttributeKeyHwID               HwNetworkBandwidthUtilizationMetricAttributeKey = "hw.id"
	HwNetworkBandwidthUtilizationMetricAttributeKeyNetworkIoDirection HwNetworkBandwidthUtilizationMetricAttributeKey = "network.io.direction"
)

// HwNetworkBandwidthUtilizationMetricConfig provides config for the hw.network.bandwidth.utilization metric.
type HwNetworkBandwidthUtilizationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                            `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []HwNetworkBandwidthUtilizationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *HwNetworkBandwidthUtilizationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *HwNetworkBandwidthUtilizationMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case HwNetworkBandwidthUtilizationMetricAttributeKeyHwID, HwNetworkBandwidthUtilizationMetricAttributeKeyNetworkIoDirection:
		default:
			return fmt.Errorf("metric hw.network.bandwidth.utilization doesn't have an attribute %v, valid attributes: [hw.id, network.io.direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// HwNetworkIoMetricAttributeKey specifies the key of an attribute for the hw.network.io metric.
type HwNetworkIoMetricAttributeKey string

const (
	HwNetworkIoMetricAttributeKeyHwID               HwNetworkIoMetricAttributeKey = "hw.id"
	HwNetworkIoMetricAttributeKeyHwName             HwNetworkIoMetricAttributeKey = "hw.name"
	HwNetworkIoMetricAttributeKeyNetworkIoDirection HwNetworkIoMetricAttributeKey = "network.io.direction"
)

// HwNetworkIoMetricConfig provides config for the hw.network.io metric.
type HwNetworkIoMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []HwNetworkIoMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *HwNetworkIoMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *HwNetworkIoMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case HwNetworkIoMetricAttributeKeyHwID, HwNetworkIoMetricAttributeKeyHwName, HwNetworkIoMetricAttributeKeyNetworkIoDirection:
		default:
			return fmt.Errorf("metric hw.network.io doesn't have an attribute %v, valid attributes: [hw.id, hw.name, network.io.direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// HwNetworkPacketsMetricAttributeKey specifies the key of an attribute for the hw.network.packets metric.
type HwNetworkPacketsMetricAttributeKey string

const (
	HwNetworkPacketsMetricAttributeKeyHwID               HwNetworkPacketsMetricAttributeKey = "hw.id"
	HwNetworkPacketsMetricAttributeKeyHwName             HwNetworkPacketsMetricAttributeKey = "hw.name"
	HwNetworkPacketsMetricAttributeKeyNetworkIoDirection HwNetworkPacketsMetricAttributeKey = "network.io.direction"
)

// HwNetworkPacketsMetricConfig provides config for the hw.network.packets metric.
type HwNetworkPacketsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                               `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []HwNetworkPacketsMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *HwNetworkPacketsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *HwNetworkPacketsMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case HwNetworkPacketsMetricAttributeKeyHwID, HwNetworkPacketsMetricAttributeKeyHwName, HwNetworkPacketsMetricAttributeKeyNetworkIoDirection:
		default:
			return fmt.Errorf("metric hw.network.packets doesn't have an attribute %v, valid attributes: [hw.id, hw.name, network.io.direction]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// HwNetworkUpMetricAttributeKey specifies the key of an attribute for the hw.network.up metric.
type HwNetworkUpMetricAttributeKey string

const (
	HwNetworkUpMetricAttributeKeyHwID   HwNetworkUpMetricAttributeKey = "hw.id"
	HwNetworkUpMetricAttributeKeyHwName HwNetworkUpMetricAttributeKey = "hw.name"
)

// HwNetworkUpMetricConfig provides config for the hw.network.up metric.
type HwNetworkUpMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                          `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []HwNetworkUpMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *HwNetworkUpMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *HwNetworkUpMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case HwNetworkUpMetricAttributeKeyHwID, HwNetworkUpMetricAttributeKeyHwName:
		default:
			return fmt.Errorf("metric hw.network.up doesn't have an attribute %v, valid attributes: [hw.id, hw.name]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// MetricsConfig provides config for fritzbox metrics.
type MetricsConfig struct {
	FritzboxDeviceUptime          FritzboxDeviceUptimeMetricConfig          `mapstructure:"fritzbox.device.uptime"`
	FritzboxDslAttenuation        FritzboxDslAttenuationMetricConfig        `mapstructure:"fritzbox.dsl.attenuation"`
	FritzboxDslErrorSeconds       FritzboxDslErrorSecondsMetricConfig       `mapstructure:"fritzbox.dsl.error_seconds"`
	FritzboxDslNoiseMargin        FritzboxDslNoiseMarginMetricConfig        `mapstructure:"fritzbox.dsl.noise_margin"`
	FritzboxDslRateCurrent        FritzboxDslRateCurrentMetricConfig        `mapstructure:"fritzbox.dsl.rate.current"`
	FritzboxDslRateMax            FritzboxDslRateMaxMetricConfig            `mapstructure:"fritzbox.dsl.rate.max"`
	FritzboxHostsActive           FritzboxHostsActiveMetricConfig           `mapstructure:"fritzbox.hosts.active"`
	FritzboxHostsInfo             FritzboxHostsInfoMetricConfig             `mapstructure:"fritzbox.hosts.info"`
	FritzboxHostsTotal            FritzboxHostsTotalMetricConfig            `mapstructure:"fritzbox.hosts.total"`
	FritzboxWanConnectionStatus   FritzboxWanConnectionStatusMetricConfig   `mapstructure:"fritzbox.wan.connection.status"`
	FritzboxWanConnectionUptime   FritzboxWanConnectionUptimeMetricConfig   `mapstructure:"fritzbox.wan.connection.uptime"`
	FritzboxWanExternalIP         FritzboxWanExternalIPMetricConfig         `mapstructure:"fritzbox.wan.external_ip"`
	FritzboxWlanChannel           FritzboxWlanChannelMetricConfig           `mapstructure:"fritzbox.wlan.channel"`
	FritzboxWlanClients           FritzboxWlanClientsMetricConfig           `mapstructure:"fritzbox.wlan.clients"`
	HwErrors                      HwErrorsMetricConfig                      `mapstructure:"hw.errors"`
	HwNetworkBandwidthLimit       HwNetworkBandwidthLimitMetricConfig       `mapstructure:"hw.network.bandwidth.limit"`
	HwNetworkBandwidthUtilization HwNetworkBandwidthUtilizationMetricConfig `mapstructure:"hw.network.bandwidth.utilization"`
	HwNetworkIo                   HwNetworkIoMetricConfig                   `mapstructure:"hw.network.io"`
	HwNetworkPackets              HwNetworkPacketsMetricConfig              `mapstructure:"hw.network.packets"`
	HwNetworkUp                   HwNetworkUpMetricConfig                   `mapstructure:"hw.network.up"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		FritzboxDeviceUptime: FritzboxDeviceUptimeMetricConfig{
			Enabled: true,
		},
		FritzboxDslAttenuation: FritzboxDslAttenuationMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []FritzboxDslAttenuationMetricAttributeKey{FritzboxDslAttenuationMetricAttributeKeyNetworkIoDirection},
		},
		FritzboxDslErrorSeconds: FritzboxDslErrorSecondsMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []FritzboxDslErrorSecondsMetricAttributeKey{FritzboxDslErrorSecondsMetricAttributeKeySeverity},
		},
		FritzboxDslNoiseMargin: FritzboxDslNoiseMarginMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []FritzboxDslNoiseMarginMetricAttributeKey{FritzboxDslNoiseMarginMetricAttributeKeyNetworkIoDirection},
		},
		FritzboxDslRateCurrent: FritzboxDslRateCurrentMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []FritzboxDslRateCurrentMetricAttributeKey{FritzboxDslRateCurrentMetricAttributeKeyNetworkIoDirection},
		},
		FritzboxDslRateMax: FritzboxDslRateMaxMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []FritzboxDslRateMaxMetricAttributeKey{FritzboxDslRateMaxMetricAttributeKeyNetworkIoDirection},
		},
		FritzboxHostsActive: FritzboxHostsActiveMetricConfig{
			Enabled: false,
		},
		FritzboxHostsInfo: FritzboxHostsInfoMetricConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []FritzboxHostsInfoMetricAttributeKey{FritzboxHostsInfoMetricAttributeKeyHostname, FritzboxHostsInfoMetricAttributeKeyIP, FritzboxHostsInfoMetricAttributeKeyMac, FritzboxHostsInfoMetricAttributeKeyInterfaceType, FritzboxHostsInfoMetricAttributeKeyActive, FritzboxHostsInfoMetricAttributeKeyGuest, FritzboxHostsInfoMetricAttributeKeyFriendlyName},
		},
		FritzboxHostsTotal: FritzboxHostsTotalMetricConfig{
			Enabled: true,
		},
		FritzboxWanConnectionStatus: FritzboxWanConnectionStatusMetricConfig{
			Enabled: true,
		},
		FritzboxWanConnectionUptime: FritzboxWanConnectionUptimeMetricConfig{
			Enabled: true,
		},
		FritzboxWanExternalIP: FritzboxWanExternalIPMetricConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []FritzboxWanExternalIPMetricAttributeKey{FritzboxWanExternalIPMetricAttributeKeyExternalIP},
		},
		FritzboxWlanChannel: FritzboxWlanChannelMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []FritzboxWlanChannelMetricAttributeKey{FritzboxWlanChannelMetricAttributeKeyHwID, FritzboxWlanChannelMetricAttributeKeySsid},
		},
		FritzboxWlanClients: FritzboxWlanClientsMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []FritzboxWlanClientsMetricAttributeKey{FritzboxWlanClientsMetricAttributeKeyHwID, FritzboxWlanClientsMetricAttributeKeySsid},
		},
		HwErrors: HwErrorsMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []HwErrorsMetricAttributeKey{HwErrorsMetricAttributeKeyHwID, HwErrorsMetricAttributeKeyErrorType, HwErrorsMetricAttributeKeyNetworkIoDirection},
		},
		HwNetworkBandwidthLimit: HwNetworkBandwidthLimitMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []HwNetworkBandwidthLimitMetricAttributeKey{HwNetworkBandwidthLimitMetricAttributeKeyHwID},
		},
		HwNetworkBandwidthUtilization: HwNetworkBandwidthUtilizationMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []HwNetworkBandwidthUtilizationMetricAttributeKey{HwNetworkBandwidthUtilizationMetricAttributeKeyHwID, HwNetworkBandwidthUtilizationMetricAttributeKeyNetworkIoDirection},
		},
		HwNetworkIo: HwNetworkIoMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []HwNetworkIoMetricAttributeKey{HwNetworkIoMetricAttributeKeyHwID, HwNetworkIoMetricAttributeKeyHwName, HwNetworkIoMetricAttributeKeyNetworkIoDirection},
		},
		HwNetworkPackets: HwNetworkPacketsMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategySum,
			EnabledAttributes:   []HwNetworkPacketsMetricAttributeKey{HwNetworkPacketsMetricAttributeKeyHwID, HwNetworkPacketsMetricAttributeKeyHwName, HwNetworkPacketsMetricAttributeKeyNetworkIoDirection},
		},
		HwNetworkUp: HwNetworkUpMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []HwNetworkUpMetricAttributeKey{HwNetworkUpMetricAttributeKeyHwID, HwNetworkUpMetricAttributeKeyHwName},
		},
	}
}

// MetricsBuilderConfig is a configuration for fritzbox metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
