// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
	testDataSetReag
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "reaggregate_set",
			metricsSet:  testDataSetReag,
			resAttrsSet: testDataSetReag,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))
			aggMap := make(map[string]string) // contains the aggregation strategies for each metric name
			aggMap["fritzbox.dsl.attenuation"] = mb.metricFritzboxDslAttenuation.config.AggregationStrategy
			aggMap["fritzbox.dsl.error_seconds"] = mb.metricFritzboxDslErrorSeconds.config.AggregationStrategy
			aggMap["fritzbox.dsl.noise_margin"] = mb.metricFritzboxDslNoiseMargin.config.AggregationStrategy
			aggMap["fritzbox.dsl.rate.current"] = mb.metricFritzboxDslRateCurrent.config.AggregationStrategy
			aggMap["fritzbox.dsl.rate.max"] = mb.metricFritzboxDslRateMax.config.AggregationStrategy
			aggMap["fritzbox.wan.external_ip"] = mb.metricFritzboxWanExternalIP.config.AggregationStrategy
			aggMap["fritzbox.wlan.channel"] = mb.metricFritzboxWlanChannel.config.AggregationStrategy
			aggMap["fritzbox.wlan.clients"] = mb.metricFritzboxWlanClients.config.AggregationStrategy
			aggMap["hw.errors"] = mb.metricHwErrors.config.AggregationStrategy
			aggMap["hw.network.bandwidth.limit"] = mb.metricHwNetworkBandwidthLimit.config.AggregationStrategy
			aggMap["hw.network.bandwidth.utilization"] = mb.metricHwNetworkBandwidthUtilization.config.AggregationStrategy
			aggMap["hw.network.io"] = mb.metricHwNetworkIo.config.AggregationStrategy
			aggMap["hw.network.packets"] = mb.metricHwNetworkPackets.config.AggregationStrategy
			aggMap["hw.network.up"] = mb.metricHwNetworkUp.config.AggregationStrategy

			expectedWarnings := 0
			if tt.metricsSet != testDataSetReag {
				assert.Equal(t, expectedWarnings, observedLogs.Len())
			}

			defaultMetricsCount := 0
			allMetricsCount := 0
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFritzboxDeviceUptimeDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFritzboxDslAttenuationDataPoint(ts, 1, AttributeNetworkIoDirectionReceive)
			if tt.name == "reaggregate_set" {
				mb.RecordFritzboxDslAttenuationDataPoint(ts, 3, AttributeNetworkIoDirectionTransmit)
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFritzboxDslErrorSecondsDataPoint(ts, 1, AttributeSeverityErrored)
			if tt.name == "reaggregate_set" {
				mb.RecordFritzboxDslErrorSecondsDataPoint(ts, 3, AttributeSeveritySeverelyErrored)
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFritzboxDslNoiseMarginDataPoint(ts, 1, AttributeNetworkIoDirectionReceive)
			if tt.name == "reaggregate_set" {
				mb.RecordFritzboxDslNoiseMarginDataPoint(ts, 3, AttributeNetworkIoDirectionTransmit)
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFritzboxDslRateCurrentDataPoint(ts, 1, AttributeNetworkIoDirectionReceive)
			if tt.name == "reaggregate_set" {
				mb.RecordFritzboxDslRateCurrentDataPoint(ts, 3, AttributeNetworkIoDirectionTransmit)
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFritzboxDslRateMaxDataPoint(ts, 1, AttributeNetworkIoDirectionReceive)
			if tt.name == "reaggregate_set" {
				mb.RecordFritzboxDslRateMaxDataPoint(ts, 3, AttributeNetworkIoDirectionTransmit)
			}

			allMetricsCount++
			mb.RecordFritzboxHostsActiveDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFritzboxHostsTotalDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFritzboxWanConnectionStatusDataPoint(ts, 1)
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFritzboxWanConnectionUptimeDataPoint(ts, 1)

			allMetricsCount++
			mb.RecordFritzboxWanExternalIPDataPoint(ts, 1, "external_ip-val")
			if tt.name == "reaggregate_set" {
				mb.RecordFritzboxWanExternalIPDataPoint(ts, 3, "external_ip-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFritzboxWlanChannelDataPoint(ts, 1, "hw.id-val", "ssid-val")
			if tt.name == "reaggregate_set" {
				mb.RecordFritzboxWlanChannelDataPoint(ts, 3, "hw.id-val-2", "ssid-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordFritzboxWlanClientsDataPoint(ts, 1, "hw.id-val", "ssid-val")
			if tt.name == "reaggregate_set" {
				mb.RecordFritzboxWlanClientsDataPoint(ts, 3, "hw.id-val-2", "ssid-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwErrorsDataPoint(ts, 1, "hw.id-val", AttributeErrorTypeFec, AttributeNetworkIoDirectionReceive)
			if tt.name == "reaggregate_set" {
				mb.RecordHwErrorsDataPoint(ts, 3, "hw.id-val-2", AttributeErrorTypeCrc, AttributeNetworkIoDirectionTransmit)
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwNetworkBandwidthLimitDataPoint(ts, 1, "hw.id-val")
			if tt.name == "reaggregate_set" {
				mb.RecordHwNetworkBandwidthLimitDataPoint(ts, 3, "hw.id-val-2")
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwNetworkBandwidthUtilizationDataPoint(ts, 1, "hw.id-val", AttributeNetworkIoDirectionReceive)
			if tt.name == "reaggregate_set" {
				mb.RecordHwNetworkBandwidthUtilizationDataPoint(ts, 3, "hw.id-val-2", AttributeNetworkIoDirectionTransmit)
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwNetworkIoDataPoint(ts, 1, "hw.id-val", "hw.name-val", AttributeNetworkIoDirectionReceive)
			if tt.name == "reaggregate_set" {
				mb.RecordHwNetworkIoDataPoint(ts, 3, "hw.id-val-2", "hw.name-val-2", AttributeNetworkIoDirectionTransmit)
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwNetworkPacketsDataPoint(ts, 1, "hw.id-val", "hw.name-val", AttributeNetworkIoDirectionReceive)
			if tt.name == "reaggregate_set" {
				mb.RecordHwNetworkPacketsDataPoint(ts, 3, "hw.id-val-2", "hw.name-val-2", AttributeNetworkIoDirectionTransmit)
			}
			defaultMetricsCount++
			allMetricsCount++
			mb.RecordHwNetworkUpDataPoint(ts, 1, "hw.id-val", "hw.name-val")
			if tt.name == "reaggregate_set" {
				mb.RecordHwNetworkUpDataPoint(ts, 3, "hw.id-val-2", "hw.name-val-2")
			}

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))
			if tt.name == "reaggregate_set" {
				assert.Empty(t, mb.metricFritzboxDslAttenuation.aggDataPoints)
				assert.Empty(t, mb.metricFritzboxDslErrorSeconds.aggDataPoints)
				assert.Empty(t, mb.metricFritzboxDslNoiseMargin.aggDataPoints)
				assert.Empty(t, mb.metricFritzboxDslRateCurrent.aggDataPoints)
				assert.Empty(t, mb.metricFritzboxDslRateMax.aggDataPoints)
				assert.Empty(t, mb.metricFritzboxWanExternalIP.aggDataPoints)
				assert.Empty(t, mb.metricFritzboxWlanChannel.aggDataPoints)
				assert.Empty(t, mb.metricFritzboxWlanClients.aggDataPoints)
				assert.Empty(t, mb.metricHwErrors.aggDataPoints)
				assert.Empty(t, mb.metricHwNetworkBandwidthLimit.aggDataPoints)
				assert.Empty(t, mb.metricHwNetworkBandwidthUtilization.aggDataPoints)
				assert.Empty(t, mb.metricHwNetworkIo.aggDataPoints)
				assert.Empty(t, mb.metricHwNetworkPackets.aggDataPoints)
				assert.Empty(t, mb.metricHwNetworkUp.aggDataPoints)
			}

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "fritzbox.device.uptime":
					assert.False(t, validatedMetrics["fritzbox.device.uptime"], "Found a duplicate in the metrics slice: fritzbox.device.uptime")
					validatedMetrics["fritzbox.device.uptime"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Time in seconds since the Fritz!Box was last restarted.", mi.Description())
					assert.Equal(t, "s", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fritzbox.dsl.attenuation":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["fritzbox.dsl.attenuation"], "Found a duplicate in the metrics slice: fritzbox.dsl.attenuation")
						validatedMetrics["fritzbox.dsl.attenuation"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "DSL line attenuation.", mi.Description())
						assert.Equal(t, "dB", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						networkIoDirectionAttrVal, ok := dp.Attributes().Get("network.io.direction")
						assert.True(t, ok)
						assert.Equal(t, "receive", networkIoDirectionAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["fritzbox.dsl.attenuation"], "Found a duplicate in the metrics slice: fritzbox.dsl.attenuation")
						validatedMetrics["fritzbox.dsl.attenuation"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "DSL line attenuation.", mi.Description())
						assert.Equal(t, "dB", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["fritzbox.dsl.attenuation"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("network.io.direction")
						assert.False(t, ok)
					}
				case "fritzbox.dsl.error_seconds":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["fritzbox.dsl.error_seconds"], "Found a duplicate in the metrics slice: fritzbox.dsl.error_seconds")
						validatedMetrics["fritzbox.dsl.error_seconds"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Cumulative count of DSL errored seconds.", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						severityAttrVal, ok := dp.Attributes().Get("severity")
						assert.True(t, ok)
						assert.Equal(t, "errored", severityAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["fritzbox.dsl.error_seconds"], "Found a duplicate in the metrics slice: fritzbox.dsl.error_seconds")
						validatedMetrics["fritzbox.dsl.error_seconds"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Cumulative count of DSL errored seconds.", mi.Description())
						assert.Equal(t, "s", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["fritzbox.dsl.error_seconds"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("severity")
						assert.False(t, ok)
					}
				case "fritzbox.dsl.noise_margin":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["fritzbox.dsl.noise_margin"], "Found a duplicate in the metrics slice: fritzbox.dsl.noise_margin")
						validatedMetrics["fritzbox.dsl.noise_margin"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "DSL noise margin (signal-to-noise ratio).", mi.Description())
						assert.Equal(t, "dB", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						networkIoDirectionAttrVal, ok := dp.Attributes().Get("network.io.direction")
						assert.True(t, ok)
						assert.Equal(t, "receive", networkIoDirectionAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["fritzbox.dsl.noise_margin"], "Found a duplicate in the metrics slice: fritzbox.dsl.noise_margin")
						validatedMetrics["fritzbox.dsl.noise_margin"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "DSL noise margin (signal-to-noise ratio).", mi.Description())
						assert.Equal(t, "dB", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["fritzbox.dsl.noise_margin"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("network.io.direction")
						assert.False(t, ok)
					}
				case "fritzbox.dsl.rate.current":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["fritzbox.dsl.rate.current"], "Found a duplicate in the metrics slice: fritzbox.dsl.rate.current")
						validatedMetrics["fritzbox.dsl.rate.current"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Current DSL sync rate.", mi.Description())
						assert.Equal(t, "bit/s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						networkIoDirectionAttrVal, ok := dp.Attributes().Get("network.io.direction")
						assert.True(t, ok)
						assert.Equal(t, "receive", networkIoDirectionAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["fritzbox.dsl.rate.current"], "Found a duplicate in the metrics slice: fritzbox.dsl.rate.current")
						validatedMetrics["fritzbox.dsl.rate.current"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Current DSL sync rate.", mi.Description())
						assert.Equal(t, "bit/s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["fritzbox.dsl.rate.current"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("network.io.direction")
						assert.False(t, ok)
					}
				case "fritzbox.dsl.rate.max":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["fritzbox.dsl.rate.max"], "Found a duplicate in the metrics slice: fritzbox.dsl.rate.max")
						validatedMetrics["fritzbox.dsl.rate.max"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Maximum attainable DSL rate.", mi.Description())
						assert.Equal(t, "bit/s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						networkIoDirectionAttrVal, ok := dp.Attributes().Get("network.io.direction")
						assert.True(t, ok)
						assert.Equal(t, "receive", networkIoDirectionAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["fritzbox.dsl.rate.max"], "Found a duplicate in the metrics slice: fritzbox.dsl.rate.max")
						validatedMetrics["fritzbox.dsl.rate.max"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Maximum attainable DSL rate.", mi.Description())
						assert.Equal(t, "bit/s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["fritzbox.dsl.rate.max"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("network.io.direction")
						assert.False(t, ok)
					}
				case "fritzbox.hosts.active":
					assert.False(t, validatedMetrics["fritzbox.hosts.active"], "Found a duplicate in the metrics slice: fritzbox.hosts.active")
					validatedMetrics["fritzbox.hosts.active"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Number of hosts currently active on the Fritz!Box network. Costs one SOAP call per host per interval.", mi.Description())
					assert.Equal(t, "{host}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fritzbox.hosts.total":
					assert.False(t, validatedMetrics["fritzbox.hosts.total"], "Found a duplicate in the metrics slice: fritzbox.hosts.total")
					validatedMetrics["fritzbox.hosts.total"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Total number of hosts known to the Fritz!Box.", mi.Description())
					assert.Equal(t, "{host}", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fritzbox.wan.connection.status":
					assert.False(t, validatedMetrics["fritzbox.wan.connection.status"], "Found a duplicate in the metrics slice: fritzbox.wan.connection.status")
					validatedMetrics["fritzbox.wan.connection.status"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "WAN connection status (1 = Connected, 0 = anything else).", mi.Description())
					assert.Equal(t, "1", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fritzbox.wan.connection.uptime":
					assert.False(t, validatedMetrics["fritzbox.wan.connection.uptime"], "Found a duplicate in the metrics slice: fritzbox.wan.connection.uptime")
					validatedMetrics["fritzbox.wan.connection.uptime"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
					assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
					assert.Equal(t, "Time in seconds the current WAN connection has been established.", mi.Description())
					assert.Equal(t, "s", mi.Unit())
					dp := mi.Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "fritzbox.wan.external_ip":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["fritzbox.wan.external_ip"], "Found a duplicate in the metrics slice: fritzbox.wan.external_ip")
						validatedMetrics["fritzbox.wan.external_ip"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Always 1; the external WAN IP address is carried in the external_ip attribute.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						externalIPAttrVal, ok := dp.Attributes().Get("external_ip")
						assert.True(t, ok)
						assert.Equal(t, "external_ip-val", externalIPAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["fritzbox.wan.external_ip"], "Found a duplicate in the metrics slice: fritzbox.wan.external_ip")
						validatedMetrics["fritzbox.wan.external_ip"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Always 1; the external WAN IP address is carried in the external_ip attribute.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["fritzbox.wan.external_ip"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("external_ip")
						assert.False(t, ok)
					}
				case "fritzbox.wlan.channel":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["fritzbox.wlan.channel"], "Found a duplicate in the metrics slice: fritzbox.wlan.channel")
						validatedMetrics["fritzbox.wlan.channel"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Channel the WLAN radio is operating on.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
						assert.True(t, ok)
						assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
						ssidAttrVal, ok := dp.Attributes().Get("ssid")
						assert.True(t, ok)
						assert.Equal(t, "ssid-val", ssidAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["fritzbox.wlan.channel"], "Found a duplicate in the metrics slice: fritzbox.wlan.channel")
						validatedMetrics["fritzbox.wlan.channel"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Channel the WLAN radio is operating on.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["fritzbox.wlan.channel"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("hw.id")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("ssid")
						assert.False(t, ok)
					}
				case "fritzbox.wlan.clients":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["fritzbox.wlan.clients"], "Found a duplicate in the metrics slice: fritzbox.wlan.clients")
						validatedMetrics["fritzbox.wlan.clients"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Number of clients currently associated with the WLAN radio.", mi.Description())
						assert.Equal(t, "{client}", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
						assert.True(t, ok)
						assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
						ssidAttrVal, ok := dp.Attributes().Get("ssid")
						assert.True(t, ok)
						assert.Equal(t, "ssid-val", ssidAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["fritzbox.wlan.clients"], "Found a duplicate in the metrics slice: fritzbox.wlan.clients")
						validatedMetrics["fritzbox.wlan.clients"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Number of clients currently associated with the WLAN radio.", mi.Description())
						assert.Equal(t, "{client}", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["fritzbox.wlan.clients"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("hw.id")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("ssid")
						assert.False(t, ok)
					}
				case "hw.errors":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["hw.errors"], "Found a duplicate in the metrics slice: hw.errors")
						validatedMetrics["hw.errors"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Number of DSL line errors encountered by the Fritz!Box WAN interface.", mi.Description())
						assert.Equal(t, "{error}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
						assert.True(t, ok)
						assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
						errorTypeAttrVal, ok := dp.Attributes().Get("error.type")
						assert.True(t, ok)
						assert.Equal(t, "fec", errorTypeAttrVal.Str())
						networkIoDirectionAttrVal, ok := dp.Attributes().Get("network.io.direction")
						assert.True(t, ok)
						assert.Equal(t, "receive", networkIoDirectionAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["hw.errors"], "Found a duplicate in the metrics slice: hw.errors")
						validatedMetrics["hw.errors"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Number of DSL line errors encountered by the Fritz!Box WAN interface.", mi.Description())
						assert.Equal(t, "{error}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["hw.errors"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("hw.id")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("error.type")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("network.io.direction")
						assert.False(t, ok)
					}
				case "hw.network.bandwidth.limit":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["hw.network.bandwidth.limit"], "Found a duplicate in the metrics slice: hw.network.bandwidth.limit")
						validatedMetrics["hw.network.bandwidth.limit"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Link speed of the Fritz!Box WAN interface.", mi.Description())
						assert.Equal(t, "By/s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
						assert.True(t, ok)
						assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["hw.network.bandwidth.limit"], "Found a duplicate in the metrics slice: hw.network.bandwidth.limit")
						validatedMetrics["hw.network.bandwidth.limit"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Link speed of the Fritz!Box WAN interface.", mi.Description())
						assert.Equal(t, "By/s", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["hw.network.bandwidth.limit"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("hw.id")
						assert.False(t, ok)
					}
				case "hw.network.bandwidth.utilization":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["hw.network.bandwidth.utilization"], "Found a duplicate in the metrics slice: hw.network.bandwidth.utilization")
						validatedMetrics["hw.network.bandwidth.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Utilization of the Fritz!Box WAN bandwidth as a fraction.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
						assert.True(t, ok)
						assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
						networkIoDirectionAttrVal, ok := dp.Attributes().Get("network.io.direction")
						assert.True(t, ok)
						assert.Equal(t, "receive", networkIoDirectionAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["hw.network.bandwidth.utilization"], "Found a duplicate in the metrics slice: hw.network.bandwidth.utilization")
						validatedMetrics["hw.network.bandwidth.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Utilization of the Fritz!Box WAN bandwidth as a fraction.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["hw.network.bandwidth.utilization"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("hw.id")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("network.io.direction")
						assert.False(t, ok)
					}
				case "hw.network.io":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["hw.network.io"], "Found a duplicate in the metrics slice: hw.network.io")
						validatedMetrics["hw.network.io"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Received and transmitted network traffic in bytes on the Fritz!Box WAN interface.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
						assert.True(t, ok)
						assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
						hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
						assert.True(t, ok)
						assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
						networkIoDirectionAttrVal, ok := dp.Attributes().Get("network.io.direction")
						assert.True(t, ok)
						assert.Equal(t, "receive", networkIoDirectionAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["hw.network.io"], "Found a duplicate in the metrics slice: hw.network.io")
						validatedMetrics["hw.network.io"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Received and transmitted network traffic in bytes on the Fritz!Box WAN interface.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["hw.network.io"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("hw.id")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("hw.name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("network.io.direction")
						assert.False(t, ok)
					}
				case "hw.network.packets":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["hw.network.packets"], "Found a duplicate in the metrics slice: hw.network.packets")
						validatedMetrics["hw.network.packets"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Received and transmitted network traffic in packets on Fritz!Box interfaces.", mi.Description())
						assert.Equal(t, "{packet}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
						assert.True(t, ok)
						assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
						hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
						assert.True(t, ok)
						assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
						networkIoDirectionAttrVal, ok := dp.Attributes().Get("network.io.direction")
						assert.True(t, ok)
						assert.Equal(t, "receive", networkIoDirectionAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["hw.network.packets"], "Found a duplicate in the metrics slice: hw.network.packets")
						validatedMetrics["hw.network.packets"] = true
						assert.Equal(t, pmetric.MetricTypeSum, mi.Type())
						assert.Equal(t, 1, mi.Sum().DataPoints().Len())
						assert.Equal(t, "Received and transmitted network traffic in packets on Fritz!Box interfaces.", mi.Description())
						assert.Equal(t, "{packet}", mi.Unit())
						assert.True(t, mi.Sum().IsMonotonic())
						assert.Equal(t, pmetric.AggregationTemporalityCumulative, mi.Sum().AggregationTemporality())
						dp := mi.Sum().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["hw.network.packets"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("hw.id")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("hw.name")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("network.io.direction")
						assert.False(t, ok)
					}
				case "hw.network.up":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["hw.network.up"], "Found a duplicate in the metrics slice: hw.network.up")
						validatedMetrics["hw.network.up"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Link status of a Fritz!Box interface (1 = up, 0 = down).", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						hwIDAttrVal, ok := dp.Attributes().Get("hw.id")
						assert.True(t, ok)
						assert.Equal(t, "hw.id-val", hwIDAttrVal.Str())
						hwNameAttrVal, ok := dp.Attributes().Get("hw.name")
						assert.True(t, ok)
						assert.Equal(t, "hw.name-val", hwNameAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["hw.network.up"], "Found a duplicate in the metrics slice: hw.network.up")
						validatedMetrics["hw.network.up"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Link status of a Fritz!Box interface (1 = up, 0 = down).", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["hw.network.up"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("hw.id")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("hw.name")
						assert.False(t, ok)
					}
				}
			}
		})
	}
}
