// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
	"slices"
	"time"
)

const (
	AggregationStrategySum = "sum"
	AggregationStrategyAvg = "avg"
	AggregationStrategyMin = "min"
	AggregationStrategyMax = "max"
)

// AttributeErrorType specifies the value error.type attribute.
type AttributeErrorType int

const (
	_ AttributeErrorType = iota
	AttributeErrorTypeFec
	AttributeErrorTypeCrc
	AttributeErrorTypeHec
)

// String returns the string representation of the AttributeErrorType.
func (av AttributeErrorType) String() string {
	switch av {
	case AttributeErrorTypeFec:
		return "fec"
	case AttributeErrorTypeCrc:
		return "crc"
	case AttributeErrorTypeHec:
		return "hec"
	}
	return ""
}

// MapAttributeErrorType is a helper map of string to AttributeErrorType attribute value.
var MapAttributeErrorType = map[string]AttributeErrorType{
	"fec": AttributeErrorTypeFec,
	"crc": AttributeErrorTypeCrc,
	"hec": AttributeErrorTypeHec,
}

// AttributeNetworkIoDirection specifies the value network.io.direction attribute.
type AttributeNetworkIoDirection int

const (
	_ AttributeNetworkIoDirection = iota
	AttributeNetworkIoDirectionReceive
	AttributeNetworkIoDirectionTransmit
)

// String returns the string representation of the AttributeNetworkIoDirection.
func (av AttributeNetworkIoDirection) String() string {
	switch av {
	case AttributeNetworkIoDirectionReceive:
		return "receive"
	case AttributeNetworkIoDirectionTransmit:
		return "transmit"
	}
	return ""
}

// MapAttributeNetworkIoDirection is a helper map of string to AttributeNetworkIoDirection attribute value.
var MapAttributeNetworkIoDirection = map[string]AttributeNetworkIoDirection{
	"receive":  AttributeNetworkIoDirectionReceive,
	"transmit": AttributeNetworkIoDirectionTransmit,
}

// AttributeSeverity specifies the value severity attribute.
type AttributeSeverity int

const (
	_ AttributeSeverity = iota
	AttributeSeverityErrored
	AttributeSeveritySeverelyErrored
)

// String returns the string representation of the AttributeSeverity.
func (av AttributeSeverity) String() string {
	switch av {
	case AttributeSeverityErrored:
		return "errored"
	case AttributeSeveritySeverelyErrored:
		return "severely_errored"
	}
	return ""
}

// MapAttributeSeverity is a helper map of string to AttributeSeverity attribute value.
var MapAttributeSeverity = map[string]AttributeSeverity{
	"errored":          AttributeSeverityErrored,
	"severely_errored": AttributeSeveritySeverelyErrored,
}

var MetricsInfo = metricsInfo{
	FritzboxDeviceUptime: metricInfo{
		Name: "fritzbox.device.uptime",
	},
	FritzboxDslAttenuation: metricInfo{
		Name:       "fritzbox.dsl.attenuation",
		Attributes: []string{"network.io.direction"},
	},
	FritzboxDslErrorSeconds: metricInfo{
		Name:       "fritzbox.dsl.error_seconds",
		Attributes: []string{"severity"},
	},
	FritzboxDslNoiseMargin: metricInfo{
		Name:       "fritzbox.dsl.noise_margin",
		Attributes: []string{"network.io.direction"},
	},
	FritzboxDslRateCurrent: metricInfo{
		Name:       "fritzbox.dsl.rate.current",
		Attributes: []string{"network.io.direction"},
	},
	FritzboxDslRateMax: metricInfo{
		Name:       "fritzbox.dsl.rate.max",
		Attributes: []string{"network.io.direction"},
	},
	FritzboxHostsActive: metricInfo{
		Name: "fritzbox.hosts.active",
	},
	FritzboxHostsInfo: metricInfo{
		Name:       "fritzbox.hosts.info",
		Attributes: []string{"hostname", "ip", "mac", "interface_type", "active", "guest", "friendly_name"},
	},
	FritzboxHostsTotal: metricInfo{
		Name: "fritzbox.hosts.total",
	},
	FritzboxWanConnectionStatus: metricInfo{
		Name: "fritzbox.wan.connection.status",
	},
	FritzboxWanConnectionUptime: metricInfo{
		Name: "fritzbox.wan.connection.uptime",
	},
	FritzboxWanExternalIP: metricInfo{
		Name:       "fritzbox.wan.external_ip",
		Attributes: []string{"external_ip"},
	},
	FritzboxWlanChannel: metricInfo{
		Name:       "fritzbox.wlan.channel",
		Attributes: []string{"hw.id", "ssid"},
	},
	FritzboxWlanClients: metricInfo{
		Name:       "fritzbox.wlan.clients",
		Attributes: []string{"hw.id", "ssid"},
	},
	HwErrors: metricInfo{
		Name:       "hw.errors",
		Attributes: []string{"hw.id", "error.type", "network.io.direction"},
	},
	HwNetworkBandwidthLimit: metricInfo{
		Name:       "hw.network.bandwidth.limit",
		Attributes: []string{"hw.id"},
	},
	HwNetworkBandwidthUtilization: metricInfo{
		Name:       "hw.network.bandwidth.utilization",
		Attributes: []string{"hw.id", "network.io.direction"},
	},
	HwNetworkIo: metricInfo{
		Name:       "hw.network.io",
		Attributes: []string{"hw.id", "hw.name", "network.io.direction"},
	},
	HwNetworkPackets: metricInfo{
		Name:       "hw.network.packets",
		Attributes: []string{"hw.id", "hw.name", "network.io.direction"},
	},
	HwNetworkUp: metricInfo{
		Name:       "hw.network.up",
		Attributes: []string{"hw.id", "hw.name"},
	},
}

type metricsInfo struct {
	FritzboxDeviceUptime          metricInfo
	FritzboxDslAttenuation        metricInfo
	FritzboxDslErrorSeconds       metricInfo
	FritzboxDslNoiseMargin        metricInfo
	FritzboxDslRateCurrent        metricInfo
	FritzboxDslRateMax            metricInfo
	FritzboxHostsActive           metricInfo
	FritzboxHostsInfo             metricInfo
	FritzboxHostsTotal            metricInfo
	FritzboxWanConnectionStatus   metricInfo
	FritzboxWanConnectionUptime   metricInfo
	FritzboxWanExternalIP         metricInfo
	FritzboxWlanChannel           metricInfo
	FritzboxWlanClients           metricInfo
	HwErrors                      metricInfo
	HwNetworkBandwidthLimit       metricInfo
	HwNetworkBandwidthUtilization metricInfo
	HwNetworkIo                   metricInfo
	HwNetworkPackets              metricInfo
	HwNetworkUp                   metricInfo
}

type metricInfo struct {
	Name       string
	Attributes []string
}

type metricFritzboxDeviceUptime struct {
	data     pmetric.Metric                   // data buffer for generated metric.
	config   FritzboxDeviceUptimeMetricConfig // metric config provided by user.
	capacity int                              // max observed number of data points added to the metric.
}

// init fills fritzbox.device.uptime metric with initial data.
func (m *metricFritzboxDeviceUptime) init() {
	m.data.SetName("fritzbox.device.uptime")
	m.data.SetDescription("Time in seconds since the Fritz!Box was last restarted.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
}

func (m *metricFritzboxDeviceUptime) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxDeviceUptime) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxDeviceUptime) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxDeviceUptime(cfg FritzboxDeviceUptimeMetricConfig) metricFritzboxDeviceUptime {
	m := metricFritzboxDeviceUptime{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxDslAttenuation struct {
	data          pmetric.Metric                     // data buffer for generated metric.
	config        FritzboxDslAttenuationMetricConfig // metric config provided by user.
	capacity      int                                // max observed number of data points added to the metric.
	aggDataPoints []float64                          // slice containing number of aggregated datapoints at each index
}

// init fills fritzbox.dsl.attenuation metric with initial data.
func (m *metricFritzboxDslAttenuation) init() {
	m.data.SetName("fritzbox.dsl.attenuation")
	m.data.SetDescription("DSL line attenuation.")
	m.data.SetUnit("dB")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricFritzboxDslAttenuation) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, networkIoDirectionAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, FritzboxDslAttenuationMetricAttributeKeyNetworkIoDirection) {
		dp.Attributes().PutStr("network.io.direction", networkIoDirectionAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxDslAttenuation) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxDslAttenuation) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxDslAttenuation(cfg FritzboxDslAttenuationMetricConfig) metricFritzboxDslAttenuation {
	m := metricFritzboxDslAttenuation{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxDslErrorSeconds struct {
	data          pmetric.Metric                      // data buffer for generated metric.
	config        FritzboxDslErrorSecondsMetricConfig // metric config provided by user.
	capacity      int                                 // max observed number of data points added to the metric.
	aggDataPoints []int64                             // slice containing number of aggregated datapoints at each index
}

// init fills fritzbox.dsl.error_seconds metric with initial data.
func (m *metricFritzboxDslErrorSeconds) init() {
	m.data.SetName("fritzbox.dsl.error_seconds")
	m.data.SetDescription("Cumulative count of DSL errored seconds.")
	m.data.SetUnit("s")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricFritzboxDslErrorSeconds) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, severityAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, FritzboxDslErrorSecondsMetricAttributeKeySeverity) {
		dp.Attributes().PutStr("severity", severityAttributeValue)
	}

	var s string
	dps := m.data.Sum().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxDslErrorSeconds) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxDslErrorSeconds) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Sum().DataPoints().At(i).SetIntValue(m.data.Sum().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxDslErrorSeconds(cfg FritzboxDslErrorSecondsMetricConfig) metricFritzboxDslErrorSeconds {
	m := metricFritzboxDslErrorSeconds{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxDslNoiseMargin struct {
	data          pmetric.Metric                     // data buffer for generated metric.
	config        FritzboxDslNoiseMarginMetricConfig // metric config provided by user.
	capacity      int                                // max observed number of data points added to the metric.
	aggDataPoints []float64                          // slice containing number of aggregated datapoints at each index
}

// init fills fritzbox.dsl.noise_margin metric with initial data.
func (m *metricFritzboxDslNoiseMargin) init() {
	m.data.SetName("fritzbox.dsl.noise_margin")
	m.data.SetDescription("DSL noise margin (signal-to-noise ratio).")
	m.data.SetUnit("dB")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricFritzboxDslNoiseMargin) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, networkIoDirectionAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, FritzboxDslNoiseMarginMetricAttributeKeyNetworkIoDirection) {
		dp.Attributes().PutStr("network.io.direction", networkIoDirectionAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxDslNoiseMargin) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxDslNoiseMargin) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxDslNoiseMargin(cfg FritzboxDslNoiseMarginMetricConfig) metricFritzboxDslNoiseMargin {
	m := metricFritzboxDslNoiseMargin{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxDslRateCurrent struct {
	data          pmetric.Metric                     // data buffer for generated metric.
	config        FritzboxDslRateCurrentMetricConfig // metric config provided by user.
	capacity      int                                // max observed number of data points added to the metric.
	aggDataPoints []int64                            // slice containing number of aggregated datapoints at each index
}

// init fills fritzbox.dsl.rate.current metric with initial data.
func (m *metricFritzboxDslRateCurrent) init() {
	m.data.SetName("fritzbox.dsl.rate.current")
	m.data.SetDescription("Current DSL sync rate.")
	m.data.SetUnit("bit/s")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricFritzboxDslRateCurrent) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, networkIoDirectionAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, FritzboxDslRateCurrentMetricAttributeKeyNetworkIoDirection) {
		dp.Attributes().PutStr("network.io.direction", networkIoDirectionAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxDslRateCurrent) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxDslRateCurrent) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxDslRateCurrent(cfg FritzboxDslRateCurrentMetricConfig) metricFritzboxDslRateCurrent {
	m := metricFritzboxDslRateCurrent{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxDslRateMax struct {
	data          pmetric.Metric                 // data buffer for generated metric.
	config        FritzboxDslRateMaxMetricConfig // metric config provided by user.
	capacity      int                            // max observed number of data points added to the metric.
	aggDataPoints []int64                        // slice containing number of aggregated datapoints at each index
}

// init fills fritzbox.dsl.rate.max metric with initial data.
func (m *metricFritzboxDslRateMax) init() {
	m.data.SetName("fritzbox.dsl.rate.max")
	m.data.SetDescription("Maximum attainable DSL rate.")
	m.data.SetUnit("bit/s")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricFritzboxDslRateMax) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, networkIoDirectionAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, FritzboxDslRateMaxMetricAttributeKeyNetworkIoDirection) {
		dp.Attributes().PutStr("network.io.direction", networkIoDirectionAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxDslRateMax) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxDslRateMax) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxDslRateMax(cfg FritzboxDslRateMaxMetricConfig) metricFritzboxDslRateMax {
	m := metricFritzboxDslRateMax{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxHostsActive struct {
	data     pmetric.Metric                  // data buffer for generated metric.
	config   FritzboxHostsActiveMetricConfig // metric config provided by user.
	capacity int                             // max observed number of data points added to the metric.
}

// init fills fritzbox.hosts.active metric with initial data.
func (m *metricFritzboxHostsActive) init() {
	m.data.SetName("fritzbox.hosts.active")
	m.data.SetDescription("Number of hosts currently active on the Fritz!Box network. Costs one SOAP call per host per interval.")
	m.data.SetUnit("{host}")
	m.data.SetEmptyGauge()
}

func (m *metricFritzboxHostsActive) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxHostsActive) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxHostsActive) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxHostsActive(cfg FritzboxHostsActiveMetricConfig) metricFritzboxHostsActive {
	m := metricFritzboxHostsActive{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxHostsInfo struct {
	data          pmetric.Metric                // data buffer for generated metric.
	config        FritzboxHostsInfoMetricConfig // metric config provided by user.
	capacity      int                           // max observed number of data points added to the metric.
	aggDataPoints []int64                       // slice containing number of aggregated datapoints at each index
}

// init fills fritzbox.hosts.info metric with initial data.
func (m *metricFritzboxHostsInfo) init() {
	m.data.SetName("fritzbox.hosts.info")
	m.data.SetDescription("One series per known host; value is always 1, attributes carry the device identity.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricFritzboxHostsInfo) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hostnameAttributeValue string, ipAttributeValue string, macAttributeValue string, interfaceTypeAttributeValue string, activeAttributeValue string, guestAttributeValue string, friendlyNameAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, FritzboxHostsInfoMetricAttributeKeyHostname) {
		dp.Attributes().PutStr("hostname", hostnameAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, FritzboxHostsInfoMetricAttributeKeyIP) {
		dp.Attributes().PutStr("ip", ipAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, FritzboxHostsInfoMetricAttributeKeyMac) {
		dp.Attributes().PutStr("mac", macAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, FritzboxHostsInfoMetricAttributeKeyInterfaceType) {
		dp.Attributes().PutStr("interface_type", interfaceTypeAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, FritzboxHostsInfoMetricAttributeKeyActive) {
		dp.Attributes().PutStr("active", activeAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, FritzboxHostsInfoMetricAttributeKeyGuest) {
		dp.Attributes().PutStr("guest", guestAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, FritzboxHostsInfoMetricAttributeKeyFriendlyName) {
		dp.Attributes().PutStr("friendly_name", friendlyNameAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxHostsInfo) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxHostsInfo) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxHostsInfo(cfg FritzboxHostsInfoMetricConfig) metricFritzboxHostsInfo {
	m := metricFritzboxHostsInfo{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxHostsTotal struct {
	data     pmetric.Metric                 // data buffer for generated metric.
	config   FritzboxHostsTotalMetricConfig // metric config provided by user.
	capacity int                            // max observed number of data points added to the metric.
}

// init fills fritzbox.hosts.total metric with initial data.
func (m *metricFritzboxHostsTotal) init() {
	m.data.SetName("fritzbox.hosts.total")
	m.data.SetDescription("Total number of hosts known to the Fritz!Box.")
	m.data.SetUnit("{host}")
	m.data.SetEmptyGauge()
}

func (m *metricFritzboxHostsTotal) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxHostsTotal) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxHostsTotal) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxHostsTotal(cfg FritzboxHostsTotalMetricConfig) metricFritzboxHostsTotal {
	m := metricFritzboxHostsTotal{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxWanConnectionStatus struct {
	data     pmetric.Metric                          // data buffer for generated metric.
	config   FritzboxWanConnectionStatusMetricConfig // metric config provided by user.
	capacity int                                     // max observed number of data points added to the metric.
}

// init fills fritzbox.wan.connection.status metric with initial data.
func (m *metricFritzboxWanConnectionStatus) init() {
	m.data.SetName("fritzbox.wan.connection.status")
	m.data.SetDescription("WAN connection status (1 = Connected, 0 = anything else).")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
}

func (m *metricFritzboxWanConnectionStatus) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxWanConnectionStatus) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxWanConnectionStatus) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxWanConnectionStatus(cfg FritzboxWanConnectionStatusMetricConfig) metricFritzboxWanConnectionStatus {
	m := metricFritzboxWanConnectionStatus{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxWanConnectionUptime struct {
	data     pmetric.Metric                          // data buffer for generated metric.
	config   FritzboxWanConnectionUptimeMetricConfig // metric config provided by user.
	capacity int                                     // max observed number of data points added to the metric.
}

// init fills fritzbox.wan.connection.uptime metric with initial data.
func (m *metricFritzboxWanConnectionUptime) init() {
	m.data.SetName("fritzbox.wan.connection.uptime")
	m.data.SetDescription("Time in seconds the current WAN connection has been established.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
}

func (m *metricFritzboxWanConnectionUptime) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxWanConnectionUptime) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxWanConnectionUptime) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxWanConnectionUptime(cfg FritzboxWanConnectionUptimeMetricConfig) metricFritzboxWanConnectionUptime {
	m := metricFritzboxWanConnectionUptime{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxWanExternalIP struct {
	data          pmetric.Metric                    // data buffer for generated metric.
	config        FritzboxWanExternalIPMetricConfig // metric config provided by user.
	capacity      int                               // max observed number of data points added to the metric.
	aggDataPoints []int64                           // slice containing number of aggregated datapoints at each index
}

// init fills fritzbox.wan.external_ip metric with initial data.
func (m *metricFritzboxWanExternalIP) init() {
	m.data.SetName("fritzbox.wan.external_ip")
	m.data.SetDescription("Always 1; the external WAN IP address is carried in the external_ip attribute.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricFritzboxWanExternalIP) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, externalIPAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, FritzboxWanExternalIPMetricAttributeKeyExternalIP) {
		dp.Attributes().PutStr("external_ip", externalIPAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxWanExternalIP) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxWanExternalIP) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxWanExternalIP(cfg FritzboxWanExternalIPMetricConfig) metricFritzboxWanExternalIP {
	m := metricFritzboxWanExternalIP{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxWlanChannel struct {
	data          pmetric.Metric                  // data buffer for generated metric.
	config        FritzboxWlanChannelMetricConfig // metric config provided by user.
	capacity      int                             // max observed number of data points added to the metric.
	aggDataPoints []int64                         // slice containing number of aggregated datapoints at each index
}

// init fills fritzbox.wlan.channel metric with initial data.
func (m *metricFritzboxWlanChannel) init() {
	m.data.SetName("fritzbox.wlan.channel")
	m.data.SetDescription("Channel the WLAN radio is operating on.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricFritzboxWlanChannel) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string, ssidAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, FritzboxWlanChannelMetricAttributeKeyHwID) {
		dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, FritzboxWlanChannelMetricAttributeKeySsid) {
		dp.Attributes().PutStr("ssid", ssidAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxWlanChannel) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxWlanChannel) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxWlanChannel(cfg FritzboxWlanChannelMetricConfig) metricFritzboxWlanChannel {
	m := metricFritzboxWlanChannel{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricFritzboxWlanClients struct {
	data          pmetric.Metric                  // data buffer for generated metric.
	config        FritzboxWlanClientsMetricConfig // metric config provided by user.
	capacity      int                             // max observed number of data points added to the metric.
	aggDataPoints []int64                         // slice containing number of aggregated datapoints at each index
}

// init fills fritzbox.wlan.clients metric with initial data.
func (m *metricFritzboxWlanClients) init() {
	m.data.SetName("fritzbox.wlan.clients")
	m.data.SetDescription("Number of clients currently associated with the WLAN radio.")
	m.data.SetUnit("{client}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricFritzboxWlanClients) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string, ssidAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, FritzboxWlanClientsMetricAttributeKeyHwID) {
		dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, FritzboxWlanClientsMetricAttributeKeySsid) {
		dp.Attributes().PutStr("ssid", ssidAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricFritzboxWlanClients) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricFritzboxWlanClients) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricFritzboxWlanClients(cfg FritzboxWlanClientsMetricConfig) metricFritzboxWlanClients {
	m := metricFritzboxWlanClients{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwErrors struct {
	data          pmetric.Metric       // data buffer for generated metric.
	config        HwErrorsMetricConfig // metric config provided by user.
	capacity      int                  // max observed number of data points added to the metric.
	aggDataPoints []int64              // slice containing number of aggregated datapoints at each index
}

// init fills hw.errors metric with initial data.
func (m *metricHwErrors) init() {
	m.data.SetName("hw.errors")
	m.data.SetDescription("Number of DSL line errors encountered by the Fritz!Box WAN interface.")
	m.data.SetUnit("{error}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricHwErrors) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string, errorTypeAttributeValue string, networkIoDirectionAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, HwErrorsMetricAttributeKeyHwID) {
		dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, HwErrorsMetricAttributeKeyErrorType) {
		dp.Attributes().PutStr("error.type", errorTypeAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, HwErrorsMetricAttributeKeyNetworkIoDirection) {
		dp.Attributes().PutStr("network.io.direction", networkIoDirectionAttributeValue)
	}

	var s string
	dps := m.data.Sum().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwErrors) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwErrors) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Sum().DataPoints().At(i).SetIntValue(m.data.Sum().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwErrors(cfg HwErrorsMetricConfig) metricHwErrors {
	m := metricHwErrors{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwNetworkBandwidthLimit struct {
	data          pmetric.Metric                      // data buffer for generated metric.
	config        HwNetworkBandwidthLimitMetricConfig // metric config provided by user.
	capacity      int                                 // max observed number of data points added to the metric.
	aggDataPoints []int64                             // slice containing number of aggregated datapoints at each index
}

// init fills hw.network.bandwidth.limit metric with initial data.
func (m *metricHwNetworkBandwidthLimit) init() {
	m.data.SetName("hw.network.bandwidth.limit")
	m.data.SetDescription("Link speed of the Fritz!Box WAN interface.")
	m.data.SetUnit("By/s")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricHwNetworkBandwidthLimit) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, HwNetworkBandwidthLimitMetricAttributeKeyHwID) {
		dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwNetworkBandwidthLimit) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwNetworkBandwidthLimit) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwNetworkBandwidthLimit(cfg HwNetworkBandwidthLimitMetricConfig) metricHwNetworkBandwidthLimit {
	m := metricHwNetworkBandwidthLimit{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwNetworkBandwidthUtilization struct {
	data          pmetric.Metric                            // data buffer for generated metric.
	config        HwNetworkBandwidthUtilizationMetricConfig // metric config provided by user.
	capacity      int                                       // max observed number of data points added to the metric.
	aggDataPoints []float64                                 // slice containing number of aggregated datapoints at each index
}

// init fills hw.network.bandwidth.utilization metric with initial data.
func (m *metricHwNetworkBandwidthUtilization) init() {
	m.data.SetName("hw.network.bandwidth.utilization")
	m.data.SetDescription("Utilization of the Fritz!Box WAN bandwidth as a fraction.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricHwNetworkBandwidthUtilization) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, hwIDAttributeValue string, networkIoDirectionAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, HwNetworkBandwidthUtilizationMetricAttributeKeyHwID) {
		dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, HwNetworkBandwidthUtilizationMetricAttributeKeyNetworkIoDirection) {
		dp.Attributes().PutStr("network.io.direction", networkIoDirectionAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetDoubleValue(dpi.DoubleValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.DoubleValue() > val {
					dpi.SetDoubleValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.DoubleValue() < val {
					dpi.SetDoubleValue(val)
				}
				return
			}
		}
	}

	dp.SetDoubleValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwNetworkBandwidthUtilization) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwNetworkBandwidthUtilization) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetDoubleValue(m.data.Gauge().DataPoints().At(i).DoubleValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwNetworkBandwidthUtilization(cfg HwNetworkBandwidthUtilizationMetricConfig) metricHwNetworkBandwidthUtilization {
	m := metricHwNetworkBandwidthUtilization{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwNetworkIo struct {
	data          pmetric.Metric          // data buffer for generated metric.
	config        HwNetworkIoMetricConfig // metric config provided by user.
	capacity      int                     // max observed number of data points added to the metric.
	aggDataPoints []int64                 // slice containing number of aggregated datapoints at each index
}

// init fills hw.network.io metric with initial data.
func (m *metricHwNetworkIo) init() {
	m.data.SetName("hw.network.io")
	m.data.SetDescription("Received and transmitted network traffic in bytes on the Fritz!Box WAN interface.")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricHwNetworkIo) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwNameAttributeValue string, networkIoDirectionAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, HwNetworkIoMetricAttributeKeyHwID) {
		dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, HwNetworkIoMetricAttributeKeyHwName) {
		dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, HwNetworkIoMetricAttributeKeyNetworkIoDirection) {
		dp.Attributes().PutStr("network.io.direction", networkIoDirectionAttributeValue)
	}

	var s string
	dps := m.data.Sum().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwNetworkIo) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwNetworkIo) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Sum().DataPoints().At(i).SetIntValue(m.data.Sum().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwNetworkIo(cfg HwNetworkIoMetricConfig) metricHwNetworkIo {
	m := metricHwNetworkIo{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwNetworkPackets struct {
	data          pmetric.Metric               // data buffer for generated metric.
	config        HwNetworkPacketsMetricConfig // metric config provided by user.
	capacity      int                          // max observed number of data points added to the metric.
	aggDataPoints []int64                      // slice containing number of aggregated datapoints at each index
}

// init fills hw.network.packets metric with initial data.
func (m *metricHwNetworkPackets) init() {
	m.data.SetName("hw.network.packets")
	m.data.SetDescription("Received and transmitted network traffic in packets on Fritz!Box interfaces.")
	m.data.SetUnit("{packet}")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
	m.data.Sum().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricHwNetworkPackets) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwNameAttributeValue string, networkIoDirectionAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, HwNetworkPacketsMetricAttributeKeyHwID) {
		dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, HwNetworkPacketsMetricAttributeKeyHwName) {
		dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, HwNetworkPacketsMetricAttributeKeyNetworkIoDirection) {
		dp.Attributes().PutStr("network.io.direction", networkIoDirectionAttributeValue)
	}

	var s string
	dps := m.data.Sum().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwNetworkPackets) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwNetworkPackets) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Sum().DataPoints().At(i).SetIntValue(m.data.Sum().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwNetworkPackets(cfg HwNetworkPacketsMetricConfig) metricHwNetworkPackets {
	m := metricHwNetworkPackets{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricHwNetworkUp struct {
	data          pmetric.Metric          // data buffer for generated metric.
	config        HwNetworkUpMetricConfig // metric config provided by user.
	capacity      int                     // max observed number of data points added to the metric.
	aggDataPoints []int64                 // slice containing number of aggregated datapoints at each index
}

// init fills hw.network.up metric with initial data.
func (m *metricHwNetworkUp) init() {
	m.data.SetName("hw.network.up")
	m.data.SetDescription("Link status of a Fritz!Box interface (1 = up, 0 = down).")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
	m.aggDataPoints = m.aggDataPoints[:0]
}

func (m *metricHwNetworkUp) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwNameAttributeValue string) {
	if !m.config.Enabled {
		return
	}

	dp := pmetric.NewNumberDataPoint()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	if slices.Contains(m.config.EnabledAttributes, HwNetworkUpMetricAttributeKeyHwID) {
		dp.Attributes().PutStr("hw.id", hwIDAttributeValue)
	}
	if slices.Contains(m.config.EnabledAttributes, HwNetworkUpMetricAttributeKeyHwName) {
		dp.Attributes().PutStr("hw.name", hwNameAttributeValue)
	}

	var s string
	dps := m.data.Gauge().DataPoints()
	for i := 0; i < dps.Len(); i++ {
		dpi := dps.At(i)
		if dp.Attributes().Equal(dpi.Attributes()) && dp.StartTimestamp() == dpi.StartTimestamp() && dp.Timestamp() == dpi.Timestamp() {
			switch s = m.config.AggregationStrategy; s {
			case AggregationStrategySum, AggregationStrategyAvg:
				dpi.SetIntValue(dpi.IntValue() + val)
				m.aggDataPoints[i] += 1
				return
			case AggregationStrategyMin:
				if dpi.IntValue() > val {
					dpi.SetIntValue(val)
				}
				return
			case AggregationStrategyMax:
				if dpi.IntValue() < val {
					dpi.SetIntValue(val)
				}
				return
			}
		}
	}

	dp.SetIntValue(val)
	m.aggDataPoints = append(m.aggDataPoints, 1)
	dp.MoveTo(dps.AppendEmpty())
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricHwNetworkUp) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricHwNetworkUp) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		if m.config.AggregationStrategy == AggregationStrategyAvg {
			for i, aggCount := range m.aggDataPoints {
				m.data.Gauge().DataPoints().At(i).SetIntValue(m.data.Gauge().DataPoints().At(i).IntValue() / aggCount)
			}
		}
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricHwNetworkUp(cfg HwNetworkUpMetricConfig) metricHwNetworkUp {
	m := metricHwNetworkUp{config: cfg}

	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                              MetricsBuilderConfig // config of the metrics builder.
	startTime                           pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                     int                  // maximum observed number of metrics per resource.
	metricsBuffer                       pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                           component.BuildInfo  // contains version information.
	metricFritzboxDeviceUptime          metricFritzboxDeviceUptime
	metricFritzboxDslAttenuation        metricFritzboxDslAttenuation
	metricFritzboxDslErrorSeconds       metricFritzboxDslErrorSeconds
	metricFritzboxDslNoiseMargin        metricFritzboxDslNoiseMargin
	metricFritzboxDslRateCurrent        metricFritzboxDslRateCurrent
	metricFritzboxDslRateMax            metricFritzboxDslRateMax
	metricFritzboxHostsActive           metricFritzboxHostsActive
	metricFritzboxHostsInfo             metricFritzboxHostsInfo
	metricFritzboxHostsTotal            metricFritzboxHostsTotal
	metricFritzboxWanConnectionStatus   metricFritzboxWanConnectionStatus
	metricFritzboxWanConnectionUptime   metricFritzboxWanConnectionUptime
	metricFritzboxWanExternalIP         metricFritzboxWanExternalIP
	metricFritzboxWlanChannel           metricFritzboxWlanChannel
	metricFritzboxWlanClients           metricFritzboxWlanClients
	metricHwErrors                      metricHwErrors
	metricHwNetworkBandwidthLimit       metricHwNetworkBandwidthLimit
	metricHwNetworkBandwidthUtilization metricHwNetworkBandwidthUtilization
	metricHwNetworkIo                   metricHwNetworkIo
	metricHwNetworkPackets              metricHwNetworkPackets
	metricHwNetworkUp                   metricHwNetworkUp
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                              mbc,
		startTime:                           pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                       pmetric.NewMetrics(),
		buildInfo:                           settings.BuildInfo,
		metricFritzboxDeviceUptime:          newMetricFritzboxDeviceUptime(mbc.Metrics.FritzboxDeviceUptime),
		metricFritzboxDslAttenuation:        newMetricFritzboxDslAttenuation(mbc.Metrics.FritzboxDslAttenuation),
		metricFritzboxDslErrorSeconds:       newMetricFritzboxDslErrorSeconds(mbc.Metrics.FritzboxDslErrorSeconds),
		metricFritzboxDslNoiseMargin:        newMetricFritzboxDslNoiseMargin(mbc.Metrics.FritzboxDslNoiseMargin),
		metricFritzboxDslRateCurrent:        newMetricFritzboxDslRateCurrent(mbc.Metrics.FritzboxDslRateCurrent),
		metricFritzboxDslRateMax:            newMetricFritzboxDslRateMax(mbc.Metrics.FritzboxDslRateMax),
		metricFritzboxHostsActive:           newMetricFritzboxHostsActive(mbc.Metrics.FritzboxHostsActive),
		metricFritzboxHostsInfo:             newMetricFritzboxHostsInfo(mbc.Metrics.FritzboxHostsInfo),
		metricFritzboxHostsTotal:            newMetricFritzboxHostsTotal(mbc.Metrics.FritzboxHostsTotal),
		metricFritzboxWanConnectionStatus:   newMetricFritzboxWanConnectionStatus(mbc.Metrics.FritzboxWanConnectionStatus),
		metricFritzboxWanConnectionUptime:   newMetricFritzboxWanConnectionUptime(mbc.Metrics.FritzboxWanConnectionUptime),
		metricFritzboxWanExternalIP:         newMetricFritzboxWanExternalIP(mbc.Metrics.FritzboxWanExternalIP),
		metricFritzboxWlanChannel:           newMetricFritzboxWlanChannel(mbc.Metrics.FritzboxWlanChannel),
		metricFritzboxWlanClients:           newMetricFritzboxWlanClients(mbc.Metrics.FritzboxWlanClients),
		metricHwErrors:                      newMetricHwErrors(mbc.Metrics.HwErrors),
		metricHwNetworkBandwidthLimit:       newMetricHwNetworkBandwidthLimit(mbc.Metrics.HwNetworkBandwidthLimit),
		metricHwNetworkBandwidthUtilization: newMetricHwNetworkBandwidthUtilization(mbc.Metrics.HwNetworkBandwidthUtilization),
		metricHwNetworkIo:                   newMetricHwNetworkIo(mbc.Metrics.HwNetworkIo),
		metricHwNetworkPackets:              newMetricHwNetworkPackets(mbc.Metrics.HwNetworkPackets),
		metricHwNetworkUp:                   newMetricHwNetworkUp(mbc.Metrics.HwNetworkUp),
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricFritzboxDeviceUptime.emit(ils.Metrics())
	mb.metricFritzboxDslAttenuation.emit(ils.Metrics())
	mb.metricFritzboxDslErrorSeconds.emit(ils.Metrics())
	mb.metricFritzboxDslNoiseMargin.emit(ils.Metrics())
	mb.metricFritzboxDslRateCurrent.emit(ils.Metrics())
	mb.metricFritzboxDslRateMax.emit(ils.Metrics())
	mb.metricFritzboxHostsActive.emit(ils.Metrics())
	mb.metricFritzboxHostsInfo.emit(ils.Metrics())
	mb.metricFritzboxHostsTotal.emit(ils.Metrics())
	mb.metricFritzboxWanConnectionStatus.emit(ils.Metrics())
	mb.metricFritzboxWanConnectionUptime.emit(ils.Metrics())
	mb.metricFritzboxWanExternalIP.emit(ils.Metrics())
	mb.metricFritzboxWlanChannel.emit(ils.Metrics())
	mb.metricFritzboxWlanClients.emit(ils.Metrics())
	mb.metricHwErrors.emit(ils.Metrics())
	mb.metricHwNetworkBandwidthLimit.emit(ils.Metrics())
	mb.metricHwNetworkBandwidthUtilization.emit(ils.Metrics())
	mb.metricHwNetworkIo.emit(ils.Metrics())
	mb.metricHwNetworkPackets.emit(ils.Metrics())
	mb.metricHwNetworkUp.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordFritzboxDeviceUptimeDataPoint adds a data point to fritzbox.device.uptime metric.
func (mb *MetricsBuilder) RecordFritzboxDeviceUptimeDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricFritzboxDeviceUptime.recordDataPoint(mb.startTime, ts, val)
}

// RecordFritzboxDslAttenuationDataPoint adds a data point to fritzbox.dsl.attenuation metric.
func (mb *MetricsBuilder) RecordFritzboxDslAttenuationDataPoint(ts pcommon.Timestamp, val float64, networkIoDirectionAttributeValue AttributeNetworkIoDirection) {
	mb.metricFritzboxDslAttenuation.recordDataPoint(mb.startTime, ts, val, networkIoDirectionAttributeValue.String())
}

// RecordFritzboxDslErrorSecondsDataPoint adds a data point to fritzbox.dsl.error_seconds metric.
func (mb *MetricsBuilder) RecordFritzboxDslErrorSecondsDataPoint(ts pcommon.Timestamp, val int64, severityAttributeValue AttributeSeverity) {
	mb.metricFritzboxDslErrorSeconds.recordDataPoint(mb.startTime, ts, val, severityAttributeValue.String())
}

// RecordFritzboxDslNoiseMarginDataPoint adds a data point to fritzbox.dsl.noise_margin metric.
func (mb *MetricsBuilder) RecordFritzboxDslNoiseMarginDataPoint(ts pcommon.Timestamp, val float64, networkIoDirectionAttributeValue AttributeNetworkIoDirection) {
	mb.metricFritzboxDslNoiseMargin.recordDataPoint(mb.startTime, ts, val, networkIoDirectionAttributeValue.String())
}

// RecordFritzboxDslRateCurrentDataPoint adds a data point to fritzbox.dsl.rate.current metric.
func (mb *MetricsBuilder) RecordFritzboxDslRateCurrentDataPoint(ts pcommon.Timestamp, val int64, networkIoDirectionAttributeValue AttributeNetworkIoDirection) {
	mb.metricFritzboxDslRateCurrent.recordDataPoint(mb.startTime, ts, val, networkIoDirectionAttributeValue.String())
}

// RecordFritzboxDslRateMaxDataPoint adds a data point to fritzbox.dsl.rate.max metric.
func (mb *MetricsBuilder) RecordFritzboxDslRateMaxDataPoint(ts pcommon.Timestamp, val int64, networkIoDirectionAttributeValue AttributeNetworkIoDirection) {
	mb.metricFritzboxDslRateMax.recordDataPoint(mb.startTime, ts, val, networkIoDirectionAttributeValue.String())
}

// RecordFritzboxHostsActiveDataPoint adds a data point to fritzbox.hosts.active metric.
func (mb *MetricsBuilder) RecordFritzboxHostsActiveDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricFritzboxHostsActive.recordDataPoint(mb.startTime, ts, val)
}

// RecordFritzboxHostsInfoDataPoint adds a data point to fritzbox.hosts.info metric.
func (mb *MetricsBuilder) RecordFritzboxHostsInfoDataPoint(ts pcommon.Timestamp, val int64, hostnameAttributeValue string, ipAttributeValue string, macAttributeValue string, interfaceTypeAttributeValue string, activeAttributeValue string, guestAttributeValue string, friendlyNameAttributeValue string) {
	mb.metricFritzboxHostsInfo.recordDataPoint(mb.startTime, ts, val, hostnameAttributeValue, ipAttributeValue, macAttributeValue, interfaceTypeAttributeValue, activeAttributeValue, guestAttributeValue, friendlyNameAttributeValue)
}

// RecordFritzboxHostsTotalDataPoint adds a data point to fritzbox.hosts.total metric.
func (mb *MetricsBuilder) RecordFritzboxHostsTotalDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricFritzboxHostsTotal.recordDataPoint(mb.startTime, ts, val)
}

// RecordFritzboxWanConnectionStatusDataPoint adds a data point to fritzbox.wan.connection.status metric.
func (mb *MetricsBuilder) RecordFritzboxWanConnectionStatusDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricFritzboxWanConnectionStatus.recordDataPoint(mb.startTime, ts, val)
}

// RecordFritzboxWanConnectionUptimeDataPoint adds a data point to fritzbox.wan.connection.uptime metric.
func (mb *MetricsBuilder) RecordFritzboxWanConnectionUptimeDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricFritzboxWanConnectionUptime.recordDataPoint(mb.startTime, ts, val)
}

// RecordFritzboxWanExternalIPDataPoint adds a data point to fritzbox.wan.external_ip metric.
func (mb *MetricsBuilder) RecordFritzboxWanExternalIPDataPoint(ts pcommon.Timestamp, val int64, externalIPAttributeValue string) {
	mb.metricFritzboxWanExternalIP.recordDataPoint(mb.startTime, ts, val, externalIPAttributeValue)
}

// RecordFritzboxWlanChannelDataPoint adds a data point to fritzbox.wlan.channel metric.
func (mb *MetricsBuilder) RecordFritzboxWlanChannelDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string, ssidAttributeValue string) {
	mb.metricFritzboxWlanChannel.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, ssidAttributeValue)
}

// RecordFritzboxWlanClientsDataPoint adds a data point to fritzbox.wlan.clients metric.
func (mb *MetricsBuilder) RecordFritzboxWlanClientsDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string, ssidAttributeValue string) {
	mb.metricFritzboxWlanClients.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, ssidAttributeValue)
}

// RecordHwErrorsDataPoint adds a data point to hw.errors metric.
func (mb *MetricsBuilder) RecordHwErrorsDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string, errorTypeAttributeValue AttributeErrorType, networkIoDirectionAttributeValue AttributeNetworkIoDirection) {
	mb.metricHwErrors.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, errorTypeAttributeValue.String(), networkIoDirectionAttributeValue.String())
}

// RecordHwNetworkBandwidthLimitDataPoint adds a data point to hw.network.bandwidth.limit metric.
func (mb *MetricsBuilder) RecordHwNetworkBandwidthLimitDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string) {
	mb.metricHwNetworkBandwidthLimit.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue)
}

// RecordHwNetworkBandwidthUtilizationDataPoint adds a data point to hw.network.bandwidth.utilization metric.
func (mb *MetricsBuilder) RecordHwNetworkBandwidthUtilizationDataPoint(ts pcommon.Timestamp, val float64, hwIDAttributeValue string, networkIoDirectionAttributeValue AttributeNetworkIoDirection) {
	mb.metricHwNetworkBandwidthUtilization.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, networkIoDirectionAttributeValue.String())
}

// RecordHwNetworkIoDataPoint adds a data point to hw.network.io metric.
func (mb *MetricsBuilder) RecordHwNetworkIoDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwNameAttributeValue string, networkIoDirectionAttributeValue AttributeNetworkIoDirection) {
	mb.metricHwNetworkIo.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwNameAttributeValue, networkIoDirectionAttributeValue.String())
}

// RecordHwNetworkPacketsDataPoint adds a data point to hw.network.packets metric.
func (mb *MetricsBuilder) RecordHwNetworkPacketsDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwNameAttributeValue string, networkIoDirectionAttributeValue AttributeNetworkIoDirection) {
	mb.metricHwNetworkPackets.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwNameAttributeValue, networkIoDirectionAttributeValue.String())
}

// RecordHwNetworkUpDataPoint adds a data point to hw.network.up metric.
func (mb *MetricsBuilder) RecordHwNetworkUpDataPoint(ts pcommon.Timestamp, val int64, hwIDAttributeValue string, hwNameAttributeValue string) {
	mb.metricHwNetworkUp.recordDataPoint(mb.startTime, ts, val, hwIDAttributeValue, hwNameAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
