// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module go.opentelemetry.io/collector/cmd/builder

go 1.25

require (
	go.opentelemetry.io/collector/confmap/provider/envprovider v1.66.0
	go.opentelemetry.io/collector/confmap/provider/fileprovider v1.66.0
	go.opentelemetry.io/collector/confmap/provider/httpprovider v1.66.0
	go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.66.0
	go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.66.0
	github.com/mbaykara/fritzotel-receiver v0.1.0
	go.opentelemetry.io/collector/receiver/otlpreceiver v0.160.0
	go.opentelemetry.io/collector/exporter/debugexporter v0.160.0
	go.opentelemetry.io/collector/exporter/otlpexporter v0.160.0
	go.opentelemetry.io/collector/processor/batchprocessor v0.160.0
	go.opentelemetry.io/collector/service v0.160.0
	go.opentelemetry.io/collector/otelcol v0.160.0
)

require (
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/knadh/koanf/providers/confmap v0.1.0 // indirect
)





replace github.com/mbaykara/fritzotel-receiver v0.1.0 => ../..





